### PR TITLE
bump containerd to 1.5.4

### PR DESCRIPTION
**Pull request by MaxRink**
What this PR does / why we need it:
https://github.com/containerd/containerd/releases/tag/v1.5.4
Tl;dr: fixes a CVE

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by MaxRink** [comment]
Hmm, weird. looking at the logs containerd installs correctly on windows but the kubelet fails afterwards.

**Comment by CecileRobertMichon** [comment]
@jsturtevant @perithompson any ideas?

**Comment by perithompson** [comment]
It's like packer timed out on the final reboot before sysprep, and only on 2019, if it was containerd I'd expect it to effect both versions? @jsturtevant do we get any machine logs? To see if there was an error on reboot that stopped the host from booting?

**Comment by jsturtevant** [comment]
I am not seeing any errors for kubelet starting and the ansible tasks are completing successfully for both 2019 and 2004. The  failures seem to have timeouts during the final restart:

```
--> vhd-windows-2019: Timeout waiting for machine to restart.
```

This restart time hasn't been an issue before but could vary depending on the Windows updates being applied.  In aks-engine  we have the timeouts set to 10m instead of the default 5m (https://www.packer.io/docs/provisioners/windows-restart).  

We can either add a restart timeout here or in a different PR.

**Comment by CecileRobertMichon** [comment]
@jsturtevant any ideas why it would start failing on this particular PR? seems like it's still passing on other PRs, eg. https://github.com/kubernetes-sigs/image-builder/pull/645

**Comment by jsturtevant** [comment]
Unfortunately no, the timeout isn't even consistent in this PR, it failed for 2004 the first round and 2019 the second.  @marosset do you have any ideas on why it take longer from time to time? My understanding is the subset of Core Windows packages could be slightly different causing a slower update.  We've bumped aks-engine to 10 mins per restart for this reason.

**Comment by marosset** [comment]
> Unfortunately no, the timeout isn't even consistent in this PR, it failed for 2004 the first round and 2019 the second. @marosset do you have any ideas on why it take longer from time to time? My understanding is the subset of Core Windows packages could be slightly different causing a slower update. We've bumped aks-engine to 10 mins per restart for this reason.

I don't and trying to root-cause delays like that can be very time consuming :(

**Comment by jsturtevant** [comment]
@MaxRink https://github.com/kubernetes-sigs/image-builder/pull/660 merged to help resolve the timeout. could you re-base and try again?  Thanks!

**Comment by MaxRink** [comment]
done

**Comment by jsturtevant** [comment]
This error we have seen before, and thought was resolved in https://github.com/kubernetes-sigs/image-builder/pull/553. I will look into this some more.

```
ASK [systemprep : Update Windows Defender signatures] *************************[0m
[0;32m    vhd-windows-2019: fatal: [default]: FAILED! => {"changed": true, "cmd": "$service = Get-Service \"Windefend
```

/retest

**Review by CecileRobertMichon — COMMENTED** [review]
/approve

**Comment by jsturtevant** [comment]
/retest

This timeout is due to goss running in parallel for windows.  We have started to see it after enabling goss to fail. Spoke with @perithompson and we should lower the concurrency here for now and address in up stream goss.

**Pull request merged**
