### PR TITLE
images/capi: improve out-of-the-box compatibility with OpenSSH versions 8.8+ and 9.0+

### LINKED ISSUE #859: Building Flatcar SIG images on Azure with OpenSSH 9.0 fails
**What steps did you take and what happened:**

Running `FLATCAR_VERSION=current make build-azure-sig-flatcar` on version a09b089b1b344d75275cf741cafdbd877050f660 currently fails with the following error:
```
    sig-flatcar: Setting up proxy adapter for Ansible....
==> sig-flatcar: Executing Ansible: ansible-playbook -e packer_build_name="sig-flatcar" -e packer_builder_type=azure-arm --ssh-extra-args '-o IdentitiesOnly=yes' --extra-vars containerd_url=https://github.com/containerd/containerd/releases/download/v1.6.1/cri-containerd-cni-1.6.1-linux-amd64.tar.gz containerd_sha256=e01da1ad4a41a71e0fef52b1f0ed08980b808f1d7c904c9956c24afb8236d6f0 pause_image=k8s.gcr.io/pause:3.6 containerd_additional_settings= containerd_cri_socket=/var/run/containerd/containerd.sock containerd_version=1.6.1 crictl_url=https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.23.0/crictl-v1.23.0-linux-amd64.tar.gz crictl_sha256=b754f83c80acdc75f93aba191ff269da6be45d0fc2d3f4079704e7d1424f1ca8 crictl_source_type=http custom_role= custom_role_names="" disable_public_repos=false extra_debs= extra_repos= extra_rpms= http_proxy= https_proxy= kubeadm_template=etc/kubeadm.yml kubernetes_cni_http_source=https://github.com/containernetworking/plugins/releases/download kubernetes_cni_http_checksum=sha256:https://storage.googleapis.com/k8s-artifacts-cni/release/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz.sha256 kubernetes_http_source=https://dl.k8s.io/release kubernetes_container_registry=k8s.gcr.io kubernetes_rpm_repo=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 kubernetes_rpm_gpg_key="https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg" kubernetes_rpm_gpg_check=True kubernetes_deb_repo="https://apt.kubernetes.io/ kubernetes-xenial" kubernetes_deb_gpg_key=https://packages.cloud.google.com/apt/doc/apt-key.gpg kubernetes_cni_deb_version=0.8.7-00 kubernetes_cni_rpm_version=0.8.7-0 kubernetes_cni_semver=v0.8.7 kubernetes_cni_source_type=http kubernetes_semver=v1.21.10 kubernetes_source_type=http kubernetes_load_additional_imgs=false kubernetes_deb_version=1.21.10-00 kubernetes_rpm_version=1.21.10-0 no_proxy= pip_conf_file= python_path=/opt/pypy/site-packages redhat_epel_rpm=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm epel_rpm_gpg_key= reenable_public_repos=true remove_extra_repos=false systemd_prefix=/etc/systemd sysusr_prefix=/opt sysusrlocal_prefix=/opt load_additional_components=false additional_registry_images=false additional_registry_images_list= additional_url_images=false additional_url_images_list= additional_executables=false additional_executables_list= additional_executables_destination_path= build_target=virt --extra-vars ansible_python_interpreter=/opt/pypy/bin/pypy --extra-vars  -e ansible_ssh_private_key_file=/tmp/ansible-key1464663093 -i /tmp/packer-provisioner-ansible1359111898 /home/invidian/data/workspaces/clusterapi-flatcar/image-builder/images/capi/ansible/node.yml
    sig-flatcar:
    sig-flatcar: PLAY [all] *********************************************************************
    sig-flatcar:
    sig-flatcar: TASK [Gathering Facts] *********************************************************
    sig-flatcar: fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via scp: Warning: Permanently added '[127.0.0.1]:40711' (RSA) to the list of known hosts.\r\nbash: line 1: /usr/lib/sftp-server: No such file or directory\nscp: Connection closed\r\n", "unreachable": true}
    sig-flatcar:
    sig-flatcar: PLAY RECAP *********************************************************************
    sig-flatcar: default                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
<omitted>
Build 'sig-flatcar' errored after 5 minutes 873 milliseconds: Error executing Ansible: Non-zero exit status: exit status 4
```

**What did you expect to happen:**

Build do succeed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`): Arch Linux
- Packer Version: 1.8.0
- Packer Provider: 
- Ansible Version: core 2.11.5
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### LINKED ISSUE #905: Workaround SSH error "no matching host key type found. Their offer: ssh-rsa"
**What steps did you take and what happened:**

Right now, if one builds the CAPI images with OpenSSH version 8.8+ on the host system, the environment variable below is required to make provisioning work. This is because OpenSSH starting from version [8.8](https://www.openssh.com/txt/release-8.8) has disabled `ssh-rsa` algorithm from default configuration and this is what Ansible plugin for Packer [still generates](https://github.com/hashicorp/packer-plugin-ansible/issues/69).

```console
ANSIBLE_SSH_ARGS="-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa"
```

**What did you expect to happen:**

Builds to work on modern systems out of the box.

**Anything else you would like to add:**

I suggest we commit those arguments as default ones until upstream issue is not resolved.

As an alternative, we could try disabling Ansible provisioner proxy, bypassing local keys generation completely. I don't know what side effects that creates though.

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)): Image Builder for Cluster API

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`): Arch Linux
- Packer Version: 1.8.1
- Packer Provider:
- Ansible Version: 2.11.5

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
CC @kopiczko

### PR DESCRIPTION
**Pull request by invidian**
**What this PR does / why we need it:**

This commit improves out-of-the-box compatibility with OpenSSH versions 8.8+ and 9.0+ by fixing build errors when one tries to build CAPI images with new enough OpenSSH version on building host machine.

This PR replaces #907, which got stalled and we agreed with me replacing it. I'm interested in this PR being merged, as this is the last remaining patch to be able to build Flatcar CAPZ images with master version of image-builder. Other related PRs were #1028 and #929.

**Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):**

Fixes #859
Fixes #905 
Closes #907
Closes #1014

**Additional context:**

CC @jsturtevant @mboersma since you actively reviewed my previous PR, although I know this patches are not strictly Azure-related.

CC @johananl @kopiczko @jepio for visibility.

### CODE REVIEW

**Comment by kopiczko** [comment]
LGTM

**Review by mboersma — COMMENTED** [review]
I tested this in the CAPZ Ubuntu+Windows build pipeline as well as locally on my Mac, and everything still works. 👍🏻 

@invidian can you squash the commits?

**Comment by invidian** [comment]
>I tested this in the CAPZ Ubuntu+Windows build pipeline as well as locally on my Mac, and everything still works. 👍🏻

> @invidian can you squash the commits?

Thanks for having a look. I squashed the commits.

**Review by mboersma — COMMENTED** [review]
/lgtm
/assign @jsturtevant @kkeshavamurthy

**Comment by mboersma** [comment]
> Failed to open /logs/process-log.txt: open /logs/process-log.txt: no such file or directory

I saw this failure today on a PR in CAPZ as well. Looks like `prow` is having some issues.

**Comment by invidian** [comment]
@mboersma everything is green now, thanks for retesting.

**Comment by mboersma** [comment]
@jsturtevant @kkeshavamurthy do these SSH changes look ok to you?

**Review by mboersma — APPROVED** [review]
/approve

**Pull request merged**
