### PR TITLE
Add `use_internal_ip` to gce's packer.json

### LINKED ISSUE #1055: [GCP CAPI] Adding support for packer to use instance's internal ip
**Is your feature request related to a problem? Please describe.**
Packer uses the external IP address of the GCE instance in its default behavior.

However, in some environments, SSH connections to instances using the external IPs may be blocked by the GCP project's firewall. In such environments `make`will fail due to timeout.

```bash
user@management:~/develop/image-builder/images/capi$ make build-gce-ubuntu-2004
hack/ensure-ansible.sh
Starting galaxy collection install process
Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`.
hack/ensure-packer.sh
hack/ensure-goss.sh
Right version of binary present
packer build -var-file="/home/user/develop/image-builder/images/capi/packer/config/kubernetes.json"  -var-file="/home/user/develop/image-builder/images/capi/packer/config/cni.json"  -var-file="/home/user/develop/image-builder/images/capi/packer/config/containerd.json"  -var-file="/home/user/develop/image-builder/images/capi/packer/config/wasm-shims.json"  -var-file="/home/user/develop/image-builder/images/capi/packer/config/ansible-args.json"  -var-file="/home/user/develop/image-builder/images/capi/packer/config/goss-args.json"  -var-file="/home/user/develop/image-builder/images/capi/packer/config/common.json"  -var-file="/home/user/develop/image-builder/images/capi/packer/config/additional_components.json"  -color=true -var-file="/home/user/develop/image-builder/images/capi/packer/gce/ubuntu-2004.json"  packer/gce/packer.json
ubuntu-2004: output will be in this color.

==> ubuntu-2004: Checking image does not exist...
==> ubuntu-2004: Creating temporary RSA SSH key for instance...
==> ubuntu-2004: Using image: ubuntu-2004-focal-v20230104
==> ubuntu-2004: Creating instance...
    ubuntu-2004: Loading zone: us-central1-a
    ubuntu-2004: Loading machine type: n1-standard-1
    ubuntu-2004: Requesting instance creation...
    ubuntu-2004: Waiting for creation operation to complete...
    ubuntu-2004: Instance has been created!
==> ubuntu-2004: Waiting for the instance to become running...
    ubuntu-2004: IP: 146.148.58.29
==> ubuntu-2004: Using SSH communicator to connect: 146.148.58.29
==> ubuntu-2004: Waiting for SSH to become available...
==> ubuntu-2004: Timeout waiting for SSH.
==> ubuntu-2004: Deleting instance...
    ubuntu-2004: Instance has been deleted!
==> ubuntu-2004: Deleting disk...
    ubuntu-2004: Disk has been deleted!
Build 'ubuntu-2004' errored after 6 minutes 26 seconds: Timeout waiting for SSH.

==> Wait completed after 6 minutes 26 seconds

==> Some builds didn't complete successfully and had errors:
--> ubuntu-2004: Timeout waiting for SSH.

==> Builds finished but no artifacts were created.
make: *** [Makefile:424: build-gce-ubuntu-2004] Error 1
```

**Describe the solution you'd like**
Packer has [an option](https://developer.hashicorp.com/packer/plugins/builders/googlecompute#use_internal_ip) to give preference to internal IP addresses instead of using external IP addresses.

The current `images/capi/packer/gce/packer.json` does not define this option. Adding this option will allow developers to change the variable to allow SSH using the internal IP address.

**Describe alternatives you've considered**
This fix is not necessary if you have the developer temporarily loose security on the project side. However, that is not a smart approach.

**Additional context**
- For backward compatibility, the default value of the option should be `fasle`
- I have already confirmed that it works when I add the option.

image

/kind feature

### PR DESCRIPTION
**Pull request by RyuSA**
Allow Packer to use internal IP addr when building a GCE custom image.

What this PR does / why we need it:
Some GCP project may block SSH to instances with public IP address. Building a custom GCE image will fail doe to SSH timeout in these environments.

This PR adds `use_internal_ip` option to images/capi/gce/packer.json. This option allows Packer to use the internal IP address to build custom images. To use the option, user needs to set parameters `use_internal_ip: "true"`.

```bash
$ export PACKER_FLAGS="-var='use_internal_ip=true'"
$ make build-gce-all
```

or

```json
// images/capi/packer/gce/ubuntu-2004.json
{
  "build_name": "ubuntu-2004",
  "distribution_release": "focal",
  "distribution_version": "2004",
  // Add a parameter
  "use_internal_ip": "true",
  "zone": "us-central1-a"
}
```

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #1055

**Additional context**
The default value must be `false` for backward compatibility.
https://developer.hashicorp.com/packer/plugins/builders/googlecompute#use_internal_ip

### CODE REVIEW

**Comment by kkeshavamurthy** [comment]
@RyuSA Please run `make json-sort` to fix the ordering.

**Comment by RyuSA** [comment]
fixed with `make json-sort`

**Pull request merged**
