### PR TITLE
Point how to build an image with a specific Kubernetes version in  README.md

### PR DESCRIPTION
**Pull request by mcbenjemaa**
What this PR does / why we need it:

Point how to build an image with a specific Kubernetes version in  README.md

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Comment by jsturtevant** [comment]
is this something we could add to our doc https://image-builder.sigs.k8s.io/? Seems like a fairly common practice

**Comment by mboersma** [comment]
> is this something we could add to our doc https://image-builder.sigs.k8s.io/?

I opened an issue for this at #1322.

**Pull request merged**
