### PR TITLE
Document building with custom Kubernetes version

### LINKED ISSUE #1322: Document how to build an image with a specific k8s version
**Is your feature request related to a problem? Please describe.**

It's difficult to figure out how to build an image for a specific version of Kubernetes in image-builder. You'll see that there are hard-coded, related Packer variables in JSON files, but you won't be able to override them with a `KUBERNETES_VERSION` environment variable as you might expect.

**Describe the solution you'd like**

A recommended way is to override several related variables via `PACKER_FLAGS` on the command line when running `packer`. 

This is what PR #1300 added, but only to a provider's README. Let's document that same approach clearly in the main documentation that becomes the [Image Builder book](https://image-builder.sigs.k8s.io/).

/kind feature

### PR DESCRIPTION
**Pull request by ogghead**
What this PR does / why we need it:

* Add documentation on building with custom Kubernetes version
* Update other examples to use latest version of Kubernetes

Which issue(s) this PR fixes:
Fixes #1322

**Additional context**
* Tested on the command-line with Ubuntu and Mariner Linux, verified builds successfully

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm

**Review by AverageMarcus — COMMENTED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/approve

**Pull request merged**
