### PR TITLE
Improve unattend behaviour in certain failure situations and add unattend instructions

### PR DESCRIPTION
**Pull request by jayunit100**
Add unattend notes for windows image builder eval

### CODE REVIEW

**Comment by jayunit100** [comment]
Part of an iterative improvement to #575 ...  this way theres some guidance on what to do for product keys?

**Comment by codenrhoden** [comment]
A couple of questions...

Is the hard coded product key a dummy key or is it real? meaning, something you wouldn't want checked in. :)

I haven't looked closely at the windows builds, but is the autoattend.xml file location configurable? Meaning can you tell image-builder to point to a different one? I ask because the notes say "you will probably want to modify this file". In  general, we never want a user to modify a file that is part of the git repo -- that produces a dirty repo and will show up in build metadata (may not be true for windows builds at this time, I'm not sure). Anything that needs to be changed should be done via build parameters.

And finally, this should be squashed to a single commit.

**Comment by jayunit100** [comment]
if i remove the *users will want to modify* comment, are we all good? 

was hoping to just get this in as a first iteration on making the configuration of autoattend.xml more consumable for mortals :)

**Comment by jayunit100** [comment]
I added the time zone stuff
also added an updated to the `Download Kubernetes binaries` step so its named identically to the linux equivalent step

**Comment by codenrhoden** [comment]
> if i remove the _users will want to modify_ comment, are we all good?
> 
If it is the current state of things, better to document actual expectations rather than an ideal that doesn't exist yet.

/lgtm
/approve

**Pull request merged**
