### PR TITLE
Support building base VMDKs and build OVFs from the base VMDKs

### LINKED ISSUE #39: CAPI OVA: support starting from existing VMX
The existing build procedure for the OVA image always starts with an ISO. Some consumers of the tool may want to start with an existing image that just needs the K8s components added to it.

This would potentially allow a user to use the `vmware-iso` builder to create an OS image from scratch, which could later be used by the `vmware-vmx` builder for additional customization.

To facilitate this, the OVA build could be broken into two stages. One to generate the base/OS image, and the second to apply the K8s artifacts.

### PR DESCRIPTION
**Pull request by kkeshavamurthy**
Breaking up the OVF image building process into 2:
- Build VMDK file from the base ISO
- Use the base VMDK image to build final OVF using `vmware-vmx` builder. 

This should help in saving some time since base image can be reused. 
I have added support for `local` building only. If there is enough interest I can work on adding support for vsphere builders as well. 

Should partially fix #39 

CC: @codenrhoden @EleanorRigby

### CODE REVIEW

**Comment by EleanorRigby** [comment]
@kkeshavamurthy : I see that name of `make build` targets will change. That will be a breaking change. Also, will I have to always run base builder and then vmx builder to get the final image now?

Is there a way we can use the vmx builder if an existing vmx is specified else continue with the full build?

**Comment by kkeshavamurthy** [comment]
@EleanorRigby none of the existing build targets are changed. 2 new targets for building base VMKD and building from VMDK files are added. This will not break any existing things.

**Comment by kkeshavamurthy** [comment]
@figo, can you please approve the PR when you get a chance if everything looks good?

**Comment by figo** [comment]
@kkeshavamurthy could you add document about how those two steps build works?

**Comment by kkeshavamurthy** [comment]
@figo . Sure, should I include that in this PR or open up a new one?

**Comment by EleanorRigby** [comment]
I think you can include usage and info in our image builder gitbook with
this PR.

**Comment by kkeshavamurthy** [comment]
@figo @EleanorRigby 
Added the docs. Should be good to go.

**Comment by figo** [comment]
Thanks @kkeshavamurthy for adding the usage doc.
/lgtm
/approve

**Pull request merged**
