### PR TITLE
Use gp3 ebs volumes for AMI

### LINKED ISSUE #451: Use gp3 EBS Volumes for AMIs
https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/

### PR DESCRIPTION
**Pull request by kkeshavamurthy**
Fixes #451 

Not sure if defaulting to gp3 here will affect CAPA @randomvariable?

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
hmm Ubuntu 18.04 build failed with `Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/l/linux-meta/linux-tools-virtual_4.15.0.124.111_amd64.deb  404  Not Found [IP: 91.189.91.39 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?` 🤔 

/retest

**Comment by kkeshavamurthy** [comment]
Thanks @CecileRobertMichon . Might have been a flake.

**Comment by randomvariable** [comment]
this should be fine.
/approve

**Pull request merged**
