### PR TITLE
Update CAPV maintainers

### PR DESCRIPTION
**Pull request by randomvariable**
What this PR does / why we need it:

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
Is this intended to sync up with kubernetes-sigs/cluster-api-provider-vsphere#2082? It looks similar but adds @killianmuldoon and @sbueringer (which is fine if that's the intent, just checking).

**Comment by mboersma** [comment]
I see also kubernetes/test-infra#30190.

/lgtm

**Comment by randomvariable** [comment]
Yeah. I'm probably going to modify that CAPV PR a bit to make it clearer.

**Review by mboersma — APPROVED** [review]
/approve

**Pull request merged**
