### PR TITLE
[images/capi] Remove forked version of cloud-init

### PR DESCRIPTION
**Pull request by detiber**
This PR removes the forked version of cloud-init we were previously using

/assign @codenrhoden @akutz @figo

### CODE REVIEW

**Comment by detiber** [comment]
/hold
holding on a release of CAPA v0.3.x that includes https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1148

**Comment by detiber** [comment]
I've tested this PR against CAPA v0.3.x with https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1148

I still need to test CAPA v0.4.x against images created from this PR

**Comment by ncdc** [comment]
@detiber the CAPA PR has merged 🎉

**Comment by vincepri** [comment]
I'll port this to the GCP images once ready

**Comment by detiber** [comment]
> I'll port this to the GCP images once ready

@vincepri as far as I could tell, Goss was only being invoked for the AWS images, so unless you are planning on adding the Goss testing, it should be a noop for GCP

**Comment by ncdc** [comment]
@detiber time to shop for an approver 😉

**Comment by codenrhoden** [comment]
/approve

Thanks @detiber! Excited to see this part go away. :)

**Pull request merged**
