### PR TITLE
Remove unwanted boot-order from the containerd service

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it:***

cloud-final service already got the entries to start the containerd service as prereq [here](https://github.com/kubernetes-sigs/image-builder/blob/196c549b8f31f890f7839cdd5681c1facd78dad2/images/capi/ansible/roles/providers/files/etc/systemd/system/cloud-final.service.d/boot-order.conf#L2:L3), and entries here in the containerd is not really needed.

And there is also a scenario where cloud-unit service will be disabled post first-boot but having these entries in the containerd service will forcefully start the cloud-init because of these entries, hence these prereq is not really needed anymore.

**Additional context**

After modifying, I did deploy the image and it looks to be fine and here is the status of the service which clearly shows that containerd service is started before the cloud-final

containerd service started at `Sun 2021-12-12 09:52:58 UTC`

```shell
$ systemctl status containerd
● containerd.service - containerd container runtime
   Loaded: loaded (/etc/systemd/system/containerd.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/containerd.service.d
           └─max-tasks.conf, memory-pressure.conf
   Active: active (running) since Sun 2021-12-12 09:52:58 UTC; 1min 16s ago
     Docs: https://containerd.io
 Main PID: 1209 (containerd)
    Tasks: 96
   Memory: 811.9M
   CGroup: /system.slice/containerd.service
           ├─1209 /usr/local/bin/containerd
           ├─6550 /usr/local/bin/containerd-shim-runc-v2 -namespace k8s.io -id 2e33083493d1a261915f1f763469fd094759349711b31647e46a10f61b2cfdca -address /run/containerd/containerd.sock
           ├─6567 /usr/local/bin/containerd-shim-runc-v2 -namespace k8s.io -id 14e32e12ba1b32d5d7d9c7dacce8796cee8e94729c3a8508272efeb3d6373fd4 -address /run/containerd/containerd.sock
           ├─6597 /usr/local/bin/containerd-shim-runc-v2 -namespace k8s.io -id 4f00fe5a81f55e0e17b890636c25a8c98a59b1960a1827bb780eab8f5f22b78b -address /run/containerd/containerd.sock
           ├─6623 /usr/local/bin/containerd-shim-runc-v2 -namespace k8s.io -id 0083774f2d1e9a61a530a6b42db37ed227e04a68d4923fe9f1888f43cb90be11 -address /run/containerd/containerd.sock
           ├─6656 /usr/local/bin/containerd-shim-runc-v2 -namespace k8s.io -id 717f62e4ae7cc20bf12c9a3e826ee342d605c878835e6495b3591d065b26448e -address /run/containerd/containerd.sock
           └─7265 /usr/local/bin/containerd-shim-runc-v2 -namespace k8s.io -id 5ee2ee3a30076d25b84823d8d6d0d64110001f02ee2767b5a597ab7cbb9c2a6f -address /run/containerd/containerd.sock

Dec 12 09:54:08 ibm-powervs-1-control-plane-fnfwc containerd[1209]: time="2021-12-12T09:54:08.426513947Z" level=info msg="Finish port forwarding for \"14e32e12ba1b32d5d7d9c7dacce8796cee8e94729c3a8508>
Dec 12 09:54:08 ibm-powervs-1-control-plane-fnfwc containerd[1209]: time="2021-12-12T09:54:08.782975903Z" level=info msg="Finish port forwarding for \"14e32e12ba1b32d5d7d9c7dacce8796cee8e94729c3a8508>

```

cloud-final service started at `Sun 2021-12-12 09:54:17 UTC`

```shell
$ systemctl status cloud-final
● cloud-final.service - Execute cloud user/final scripts
   Loaded: loaded (/usr/lib/systemd/system/cloud-final.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/cloud-final.service.d
           └─boot-order.conf
   Active: active (exited) since Sun 2021-12-12 09:54:17 UTC; 11s ago
  Process: 8314 ExecStartPost=/bin/sh -c u=NetworkManager.service;   out=$(systemctl show --property=SubState $u) || exit;   [ "$out" = "SubState=running" ] || exit 0;   systemctl reload-or-try-resta>
  Process: 2034 ExecStart=/usr/bin/cloud-init modules --mode=final (code=exited, status=0/SUCCESS)
 Main PID: 2034 (code=exited, status=0/SUCCESS)

Dec 12 09:54:17 ibm-powervs-1-control-plane-fnfwc cloud-init[2034]: [2021-12-12 09:53:51]         --discovery-token-ca-cert-hash xxxxxxxxxxxxxxxxxxx >
Dec 12 09:54:17 ibm-powervs-1-control-plane-fnfwc cloud-init[2034]: [2021-12-12 09:53:51]         --control-plane
Dec 12 09:54:17 ibm-powervs-1-control-plane-fnfwc cloud-init[2034]: [2021-12-12 09:53:51]
Dec 12 09:54:17 ibm-powervs-1-control-plane-fnfwc cloud-init[2034]: [2021-12-12 09:53:51] Then you can join any number of worker nodes by running the following on each as root:
Dec 12 09:54:17 ibm-powervs-1-control-plane-fnfwc cloud-init[2034]: [2021-12-12 09:53:51]
Dec 12 09:54:17 ibm-powervs-1-control-plane-fnfwc cloud-init[2034]: [2021-12-12 09:53:51] kubeadm join 192.168.151.5:6443 --token xxxxxxxxxx \
Dec 12 09:54:17 ibm-powervs-1-control-plane-fnfwc cloud-init[2034]: [2021-12-12 09:53:51]         --discovery-token-ca-cert-hash xxxxxxxxxxxxxxxxxxx
Dec 12 09:54:17 ibm-powervs-1-control-plane-fnfwc cloud-init[2034]: [2021-12-12 09:54:17] Cloud-init v. 21.1-9.el8 running 'modules:final' at Sun, 12 Dec 2021 09:53:04 +0000. Up 17.44 seconds.
Dec 12 09:54:17 ibm-powervs-1-control-plane-fnfwc cloud-init[2034]: [2021-12-12 09:54:17] Cloud-init v. 21.1-9.el8 finished at Sun, 12 Dec 2021 09:53:51 +0000. Datasource DataSourceConfigDrive [local>
Dec 12 09:54:17 ibm-powervs-1-control-plane-fnfwc systemd[1]: Started Execute cloud user/final scripts.
```

### CODE REVIEW

**Comment by mkumatag** [comment]
```shell
==> Some builds didn't complete successfully and had errors:
--> vsphere: Post "https://vcenter.sddc-54-70-161-229.vmc.vmware.com/sdk": dial tcp 54.70.161.229:443: connect: connection timed out
```

Seems like some infra issue, lemme rerun the tests

/retest

**Comment by kkeshavamurthy** [comment]
This is from the commit msg when it was added. 
```
  - Absence of type=notify in containerd unit file
    causes cloud-final.service trigger `kubedam init` too soon and it
    fails without detecting a container runtime on machine.
  - Adding this type=notify will enable to enforce strict boot ordering
    between cloud-final and containerd
  - Adding an `After` & `Wants` containerd systemd dependency in
  cloud-final and cloud-config.
```
IIRC we had to do this to because there were issues starting up RHEL-7.

**Comment by mkumatag** [comment]
> This is from the commit msg when it was added. 
> ```
>   - Absence of type=notify in containerd unit file
>     causes cloud-final.service trigger `kubedam init` too soon and it
>     fails without detecting a container runtime on machine.
>   - Adding this type=notify will enable to enforce strict boot ordering
>     between cloud-final and containerd
>   - Adding an `After` & `Wants` containerd systemd dependency in
>   cloud-final and cloud-config.
> ```
> IIRC we had to do this to because there were issues starting up RHEL-7. 

This talks about adding dependency in the cloud-final service which is true and needed as well, but containerd service file does not need this deps,.

**Comment by mkumatag** [comment]
I see even CI is green(though not sure if it covers all the required flow), wondering if someone can take a look at this PR?

/assign @codenrhoden

**Comment by codenrhoden** [comment]
@mkumatag I think I understand what you are getting at. my memory is rusty around this one, and I know there are so many permutations on the OS's that it's a bit tricky to know that all of them are okay. I'll poke around at this one a bit and see what I can. Thanks for bringing this up.

I think @randomvariable may have some good experience around this topic as well.

**Comment by mkumatag** [comment]
> This is fine, but is it consistent across the distributions now?

they are plain systemd service files and we ship the same files across different distributions, hope things will be fine for all the distros

**Comment by mkumatag** [comment]
> > This is fine, but is it consistent across the distributions now?
> 
> they are plain systemd service files and we ship the same files across different distributions, hope things will be fine for all the distros

if no further objection, can we merge the code @codenrhoden @randomvariable

**Comment by kkeshavamurthy** [comment]
Approving this since @randomvariable @codenrhoden have no more objections. 
Sorry for the delay @mkumatag 

/lgtm
/approved

**Comment by codenrhoden** [comment]
@kkeshavamurthy haha. you are having terrible luck. :) Editing an old comment won't work either.

/approve

**Pull request merged**
