### PR TITLE
add goss checks for oci targets

### LINKED ISSUE #957: Support GOSS checks for OCI targets
**Is your feature request related to a problem? Please describe.**
Similar to the goss checks that's being done for targets in AWS, Azure & vSphere, we'd like to have support for OCI build targets (ubuntu 18.04, ubuntu 20.04 & oracle-linux-8)

**Describe the solution you'd like**
Add a packer goss provisioner after the ansible roles are run. 
Add `oci` as one of the providers in goss-vars
Add `oracle-linux` as a new os in goss-vars
Add the combo to goss-ci tests as well. 

**Describe alternatives you've considered**

**Additional context**

/kind feature

### PR DESCRIPTION
**Pull request by kkeshavamurthy**
What this PR does / why we need it:
Fixes #957 
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by kkeshavamurthy** [comment]
too many networking issues today

/test pull-azure-vhds

**Comment by SanikaGawhane** [comment]
Everything looks good!

/lgtm

**Pull request merged**
