### PR TITLE
Place RHEL kickstart files for raw builds in `http` directory

### PR DESCRIPTION
**Pull request by abhay-krishna**
By default, image-builder expects the kickstart configs to be placed inside the `<OS>/http/<OS version>` folder to match the `http_directory` field. This PR just moves the existing version folders (containing the KS config files) to the `http` directory.

### CODE REVIEW

**Review by thebsdbox — APPROVED** [review]
LGTM

**Review by drew-viles — APPROVED** [review]
/lgtm - aligns with what we're seeing in the qemu setup.

Also, note for the future, it looks like there is no packer config for RHEL 7 so it's currently not used by anything that I can see.

**Comment by abhay-krishna** [comment]
> /lgtm - aligns with what we're seeing in the qemu setup.
> 
> 
> 
> Also, note for the future, it looks like there is no packer config for RHEL 7 so it's currently not used by anything that I can see.

Yup I saw but I will include the removal in another cleanup PR where I will be removing the Ubuntu 18.04 preseed files. Noticed those ones lying around too. If you would like me to include both the cleanups in this PR, let me know.

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
