### PR TITLE
Use openvpn from community-owned registry

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

What this PR does / why we need it:
The previous image was hosted on a registry owned by VMware. I moved the image to a community-owned registry

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by sbueringer** [comment]
Would be good if we can backport this to all branches for which we still run CI. 

I'm not really involved in image-builder, so I don't know which branches these might be (happy to open PR though, if someone can give me a list of branches)

**Comment by AverageMarcus** [comment]
We don't have backport branches for old releases unfortunately.

**Pull request merged**
