### PR TITLE
Removing VirtualBox target 

### PR DESCRIPTION
**Pull request by knabben**
## Change description

Removing VirtualBox target since its not being actively maintained, important to remove in order to cleanup the repository 

## Additional context
Used by sig-windows-dev-tools without any usage.

### CODE REVIEW

**Comment by jsturtevant** [comment]
/lgtm
/hold 
for a couple weeks incase there was someone who took a dependency that we are not aware of. I will post in slack for awareness

**Comment by knabben** [comment]
@jsturtevant should this one go through? Is here for a month.

**Pull request merged**
