### PR TITLE
Truncate log files instead of deleting all dirs in /var/log

### LINKED ISSUE #314: Fix destroying all the folders in the /var/log directory tree
We destroy all the folders in the logging directory structure, would much rather do something like this:

`find /var/log/ -type f  -exec rm {} \;` so that we're not trashing folders that certain packages expect to be there, in particular with certain permissions on those folders.

Would change this section, maybe run a shell command prior to it: https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/ansible/roles/sysprep/tasks/main.yml#L131

### PR DESCRIPTION
**Pull request by EleanorRigby**
Truncate log files to zero size instead of deleting them.

fixes #314 

cc: @voor , @detiber 

/assign: @codenrhoden

### CODE REVIEW

**Comment by randomvariable** [comment]
/lgtm

Similar approach to https://github.com/chef/bento/blob/master/packer_templates/amazonlinux/scripts/cleanup.sh#L55

**Comment by EleanorRigby** [comment]
This is broken right now. The command module is not working well. Maybe, I will try the shell module.

**Comment by randomvariable** [comment]
Ah yes, this won't work unless it's shell. That said, if you use the bento variant, that should work.

**Comment by EleanorRigby** [comment]
@randomvariable : the script is quite good. It cleans up better than we do here. Do you think the whole of this can be included in this repo if I make script idempotent?

https://github.com/chef/bento/blob/master/packer_templates/amazonlinux/scripts/cleanup.sh#L55

**Comment by randomvariable** [comment]
I have used a lot of the bento stuff in the past, as it's well established. It's Apache-2 licensed, so if you can cannibilise any of it, I would.

**Comment by EleanorRigby** [comment]
> I have used a lot of the bento stuff in the past, as it's well established. It's Apache-2 licensed, so if you can cannibilise any of it, I would.

@randomvariable Okay. I will put in a separate commit for the whole script. This is fixed and ready for review again.
/unhold tested on AMI, OVA (debian redhat photon)

**Comment by EleanorRigby** [comment]
@randomvariable @codenrhoden  Are you aware of some recent changes in PR policy for `hold` tags? Unhold use to work for me (simple contributor) too. But, now it does not let me turn it off.

**Comment by randomvariable** [comment]
@EleanorRigby not sure, but we should get you set up as an org member.

**Comment by EleanorRigby** [comment]
> @EleanorRigby not sure, but we should get you set up as an org member.

That would be great. Is there some process/form I need to follow in order to apply?

**Comment by randomvariable** [comment]
@EleanorRigby : 
Start a new issue using https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E and ask for kubernetes-sigs membership. Happy to sponsor as VMware, but will need another sponsor from another company.

**Comment by bavarianbidi** [comment]
are there any plans to merge this PR in the next couple of days/weeks?

after rebase our fork to current master i also detected, that the current implementation is broken (issue #314 ).
we have done the `/var/log` cleanup in the past via [` rm -rf /var/log/*`](https://github.com/c445/image-builder/blob/caas-1910/images/capi/ansible/roles/sysprep/tasks/main.yml#L160-L161) but i prefer the `truncate` much more :-)

currently i cherry-picked this PR after rebased on current master.

**Comment by EleanorRigby** [comment]
@bavarianbidi : I will retest this PR with more OS & Provider combinations. I expect to post results next week about this testing.

**Comment by randomvariable** [comment]
Without this, a lot of the daemons aren't behaving properly. No persistent journal logs from systemd, and auditd doesn't work.

**Comment by EleanorRigby** [comment]
Unfortunately, I wasn't able to spare time this week. I will try to wrap it up soon. Should be a small change.

**Comment by EleanorRigby** [comment]
@randomvariable  This builds perfectly on Amazon Linux 2. Can you review this again? and is this PR a reason #191 is broken? maybe I misunderstood the comment on #314 .

```
==> amazon-2: Downloading spec file and debug info
    amazon-2: Downloading Goss specs from, /tmp/goss-spec.yaml and /tmp/debug-goss-spec.yaml to current dir
==> amazon-2: Stopping the source instance...
    amazon-2: Stopping instance
==> amazon-2: Waiting for the instance to stop...
==> amazon-2: Creating AMI capa-ami-amazon-2-1.17.11-00-1600461614 from instance i-0141a594bbf555678
    amazon-2: AMI: ami-06344fdd766aee73b
==> amazon-2: Waiting for AMI to become ready...
==> amazon-2: Copying/Encrypting AMI (ami-06344fdd766aee73b) to other regions...
```

**Comment by EleanorRigby** [comment]
@randomvariable @figo : Can I get review and approval on this PR?

**Comment by voor** [comment]
/lgtm 

Ran these on a few Ubuntu images directly and it appears to grab what we'd need it to.

I'd like to consider either a follow-on PR for adding something like this:

`find /var/log -type f -iname '*.1'` 

```
- name: Delete all logrotated log by rename
  shell:
    cmd: |
      find /var/log -type f -name '*.1' -exec rm {} +
```

**Pull request merged**
