### PR TITLE
OVA CI Cleanup

### PR DESCRIPTION
**Pull request by kkeshavamurthy**
What this PR does / why we need it:
1. Remove centos-7 from CI
2. Code cleanup

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by AverageMarcus** [comment]
/lgtm 
/approve

On a related note - Is it worth removing CentOS 7 (and Ubuntu 18.04 and Windows 2004) completely from the OVA provider?

**Comment by kkeshavamurthy** [comment]
> /lgtm /approve
> 
> On a related note - Is it worth removing CentOS 7 (and Ubuntu 18.04 and Windows 2004) completely from the OVA provider?

I believe we still have some customers using Centos-7 & Ubuntu 18-04. 
Regarding Win-2004 I'm not so sure. @knabben any ideas?

**Pull request merged**
