### PR TITLE
Add outscale global permission image

### PR DESCRIPTION
**Pull request by outscale-vbr**
What this PR does / why we need it:
We have to set global_permission and omi_account_ids to have the omi public instead of private.
https://docs.outscale.com/api#updateimage
https://developer.hashicorp.com/packer/plugins/builders/outscale/bsu

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by AverageMarcus** [comment]
I don't know anything about Outscale but the change looks ok to me.

/lgtm
/ok-to-test

**Comment by outscale-vbr** [comment]
@AverageMarcus I forget to sort json file.

**Comment by outscale-vbr** [comment]
@jsturtevant  Are you ok with the current changes ?

**Comment by jsturtevant** [comment]
@outscale-vbr I don't see the  `"global_permission": true,` field in the docs https://developer.hashicorp.com/packer/plugins/builders/outscale/bsu?

**Comment by kkeshavamurthy** [comment]
@outscale-vbr Do you have any update on @jsturtevant 's review?

**Comment by outscale-vbr** [comment]
@kkeshavamurthy  @jsturtevant  there are two issues to be included in next outscale packer release (v1.0.6) before this PR can be review again.
https://github.com/outscale/packer-plugin-outscale/issues/112
https://github.com/outscale/packer-plugin-outscale/issues/123

**Comment by jsturtevant** [comment]
thanks for the update, ping us once it is ready again

**Comment by outscale-vbr** [comment]
@jsturtevant 
We have done a new release for packer plugin outscale 1.1.0 which included https://github.com/outscale/packer-plugin-outscale/issues/112
https://github.com/outscale/packer-plugin-outscale/issues/123 and which include global_permission (https://developer.hashicorp.com/packer/plugins/builders/outscale/outscale-bsu) so now the PR can review.

**Comment by jsturtevant** [comment]
> [global_permission](https://developer.hashicorp.com/packer/plugins/builders/outscale/outscale-bsu#global_permission) (boolean) - This option is useful to make the OMI publicly accessible.

is there a scenario where the user will want the images to be private?  Does that setting need to be configurable?

**Comment by outscale-vbr** [comment]
@jsturtevant 
No
we have a ci to detect new version of kubernetes and build and push public image for all customer.

**Review by mboersma — APPROVED** [review]
/approve

**Pull request merged**
