### PR TITLE
Remove vSphere ESX builder for node & haproxy images

### PR DESCRIPTION
**Pull request by kkeshavamurthy**
What this PR does / why we need it:
Remove the deprecated vsphere esx builder for node & haproxy images. 

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

/assign @codenrhoden

### CODE REVIEW

**Comment by kkeshavamurthy** [comment]
Seems like we have a new VMC issue

```
 --> vsphere-clone: Error finding network: path 'sddc-cgw-network-8' resolves to multiple networks 
```

CC: @codenrhoden @randomvariable @yastij

**Comment by codenrhoden** [comment]
/test pull-ova-all

^ Not expecting this to pass.

**Comment by codenrhoden** [comment]
I think we're going to have to disable the OVA CI for now. It's going to (and already has/is) take longer than I thought to get it sorted out.

**Comment by codenrhoden** [comment]
As for removing ESX, changes look good.

One request, though. It's super pedantic, but can you retitle this PR (and change commit message) to say "remove vSphere ESX builder" rather than "deprecate"? The feature was already deprecated -- deprecation is an announcement of a future intent to remove. This PR follows through on it and actually removes it.

**Comment by codenrhoden** [comment]
@kkeshavamurthy There is no longer any reason to change the network used. You can remove that commit when you have a chance.
CI is still broken, and I'm happy to go over it with you today if possible, but the problem I was trying to work around with that suggested change is no longer an issue.

**Comment by kkeshavamurthy** [comment]
oh yeah, I forgot I changed the CI scripts in this PR. Thanks for catching it. Will revert it.

**Comment by codenrhoden** [comment]
woohoo! Yay for removals.

/lgtm

**Pull request merged**
