### PR TITLE
Update Rocky Linux 9 ISO URLs

### PR DESCRIPTION
**Pull request by 0nebody**
## Change description
Updates the Rocky 9 Linux ISO URLs to Rocky 9.4.

https://download.rockylinux.org/pub/rocky/9/isos/x86_64/

## Additional context
Failed to build with VMware Guestinfo as cloud-init is now greater than 21.3. Added a check to prevent the installation of VMware Guestinfo when not required.

### CODE REVIEW

**Review by AverageMarcus — COMMENTED** [review]
/lgtm
/assign @mboersma

**Review by mboersma — APPROVED** [review]
/retitle Update Rocky Linux 9 ISO URLs
/label tide/merge-method-squash
/lgtm
/approve

**Comment by AverageMarcus** [comment]
`tide/merge-method-squash` 😮  I had no idea we could do that! That's great!

**Comment by mboersma** [comment]
> `/label tide/merge-method-squash`

It's very useful sometimes, but I *always* have to search for the syntax.

**Pull request merged**
