### PR TITLE
Re-add windows_updates_categories variable

### PR DESCRIPTION
**Pull request by perithompson**
What this PR does / why we need it:
It looks like in the last CAPA PR one of the variables was accidentally removed, this small PR is to re-add that variable

### CODE REVIEW

**Comment by jsturtevant** [comment]
The long string is hard to catch differences.  Thanks for fixing this!

/lgtm

**Comment by perithompson** [comment]
Thanks @jsturtevant I tried to think if there was a better way but it works, even though it's a tough one to see problems with

**Pull request merged**
