### PR TITLE
Add `DEBUG` env var to turn on debug

### PR DESCRIPTION
**Pull request by fyangd**
- Set DEBUG mode for shell scripts used for image building
- Set `-debug` flag for packer build

Authored-by: Fei Yang <yangfe@vmware.com>

### CODE REVIEW

**Review by EleanorRigby — CHANGES_REQUESTED** [review]
Let's extend debug flags to all scripts under make `deps-ova` `deps-ami` and `deps-azure`
for instance, 
`/hack/ensure-goss.sh`
`/hack/ensure-packer.sh`
`/hack/ensure-ansible.sh`
to count a few.

**Comment by EleanorRigby** [comment]
Thanks for the PR. I often use the debug feature, and it will be good to have one common flag across the tool.

**Comment by fyangd** [comment]
Ok, it's been updated to include the shell scripts under `/hack`.

**Comment by EleanorRigby** [comment]
thanks for adding this global debug flag.

/lgtm

**Comment by jsturtevant** [comment]
@fyangd could you perfom a rebase?  There was also a new script file `ensure-ansible-windows.sh` added under the hack folder.  

Having the packer debug flag would be very useful :100:

**Comment by codenrhoden** [comment]
Yeah, this looks like a  nice addition @fyangd ! Thanks for adding it. Go ahead and rebase and we'll get it in.

**Comment by fyangd** [comment]
@codenrhoden thanks for reminding me!  This PR has been rebased on the latest.  Feel free to merge when ready.

**Comment by jsturtevant** [comment]
looks like a few of the recently added flatcar scripts are missing from the list, otherwise looks good.

**Comment by codenrhoden** [comment]
@fyangd Sorry to be a bother, but can you add this to the Flatcar scripts as well? I don't want to have to follow-up with a second PR on this one. I don't know of any  new incoming scripts this time around, so it shouldn't happen to you again. :)

**Comment by fyangd** [comment]
@codenrhoden Happy New Year, Travis!  It's no bother at all.  I updated this PR to include the flatcar scripts.

**Comment by codenrhoden** [comment]
/lgtm
/approve

Looks like the VHD stuff is flaky. Something to do with deb package availability. will retest in a bit.

**Pull request merged**
