### PR TITLE
images/capi/ansible/roles/node: fix Flatcar builds

### LINKED ISSUE #906: Fix etcd-network-tuning.sh location for Flatcar
**What steps did you take and what happened:**

After merging https://github.com/kubernetes-sigs/image-builder/pull/901 flatcar build fails because of read-only `/usr/local/bin`:

```
    qemu: TASK [node : Copy etcd network tuning script] **********************************
    qemu: fatal: [default]: FAILED! => {"changed": false, "checksum": "9b8498c353396b5550fde1af334e0f4030c7b7bd", "msg": "Destination /usr/local/bin not writable"}
```

**What did you expect to happen:**

Build passing.

**Anything else you would like to add:**

N/A

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`): macOS 12.4
- Packer Version: 1.8.0
- Packer Provider:
- Ansible Version: 2.12.5
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
CC @invidian

### PR DESCRIPTION
**Pull request by invidian**
What this PR does / why we need it:

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

Closes #906

**Additional context**

Extracted critical fixes from #907.

### CODE REVIEW

**Comment by invidian** [comment]
/test pull-azure-sigs

To test Flatcar build.

**Review by johananl — APPROVED** [review]
LGTM

**Comment by codenrhoden** [comment]
Thank you all for this fix!
/lgtm
/approve

**Pull request merged**
