### PR TITLE
feat: expose os_disk_size_db to allow overriding

### PR DESCRIPTION
**Pull request by mweibel**
What this PR does / why we need it:

Allows overriding VM os disk size.

### CODE REVIEW

**Comment by mweibel** [comment]
thanks @kkeshavamurthy 
Since the tests failed I was so free to add also shared image gallery `storage_account_type` as a variable, since I need this too. 

The `pull_azure_sigs` test job: I'm not sure if there's an issue with that test. It fails with `pip` not found.

**Comment by mweibel** [comment]
oh - `shared_image_gallery.storage_account_type` [requires packer 1.7.3](https://github.com/hashicorp/packer/pull/10863). I don't suppose it'd be possible to upgrade packer? :) 

I'll revert that change then.

**Comment by jsturtevant** [comment]
Looks like might be: https://github.com/hashicorp/packer-plugin-azure/issues/41#issuecomment-887035246?

**Comment by kkeshavamurthy** [comment]
I think the reason this Azure SIG test fail often is `windows-2019` and `windows-2019-containerd` SIG end up with the same SIG `Image Name`. Whichever of the 2 builds completes second tries to create a SIG Image in the Gallery with the image name that already exists and fails. 

Windows-2019 SIG image info:
```[1;32m==> sig-windows-2019: Capturing image ...[0m
[1;32m==> sig-windows-2019:  -> Compute ResourceGroupName : 'pkr-Resource-Group-jb6x9uvqz8'[0m
[1;32m==> sig-windows-2019:  -> Compute Name              : 'pkrvmjb6x9uvqz8'[0m
[1;32m==> sig-windows-2019:  -> Compute Location          : 'eastus2'[0m
[1;32m==> sig-windows-2019:  -> Image ResourceGroupName   : 'image-builder-e2e-6vf1l8'[0m
[1;32m==> sig-windows-2019:  -> Image Name                : 'capi-windows-2019-1660288896'[0m
[1;32m==> sig-windows-2019:  -> Image Location            : 'eastus2'[0m
[1;32m==> sig-windows-2019: ERROR: -> PropertyChangeNotAllowed : Changing property 'sourceVirtualMachine' is not allowed.
```

SIG Windows-2019-Containerd info:
```
[1;32m==> sig-windows-2019-containerd: Capturing image ...[0m
[1;32m==> sig-windows-2019-containerd:  -> Compute ResourceGroupName : 'pkr-Resource-Group-30uqf66a45'[0m
[1;32m==> sig-windows-2019-containerd:  -> Compute Name              : 'pkrvm30uqf66a45'[0m
[1;32m==> sig-windows-2019-containerd:  -> Compute Location          : 'eastus2'[0m
[1;32m==> sig-windows-2019-containerd:  -> Image ResourceGroupName   : 'image-builder-e2e-6vf1l8'[0m
[1;32m==> sig-windows-2019-containerd:  -> Image Name                : 'capi-windows-2019-1660288896'[0m
[1;32m==> sig-windows-2019-containerd:  -> Image Location            : 'eastus2'[0m
[1;32m==> sig-windows-2019-containerd: Publishing to Shared Image Gallery ...[0m
[1;32m==> sig-windows-2019-containerd:  -> MDI ID used for SIG publish           : '/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/image-builder-e2e-6vf1l8/providers/Microsoft.Compute/images/capi-windows-2019-1660288896'[0m
[1;32m==> sig-windows-2019-containerd:  -> SIG publish resource group            : 'image-builder-e2e-6vf1l8'[0m
[1;32m==> sig-windows-2019-containerd:  -> SIG gallery name                      : 'ClusterAPI1660288827fxzt'[0m
[1;32m==> sig-windows-2019-containerd:  -> SIG image name                        : 'capi-windows-2019-containerd'[0m
[1;32m==> sig-windows-2019-containerd:  -> SIG image version                     : '0.3.1660288896'[0m
[1;32m==> sig-windows-2019-containerd:  -> SIG replication regions               : '[eastus2]'[0m
[1;32m==> sig-windows-2019-containerd:  -> SIG image version endoflife date      : ''[0m
[1;32m==> sig-windows-2019-containerd:  -> SIG image version exclude from latest : 'false'[0m
[1;32m==> sig-windows-2019-containerd:  -> SIG replica count [1, 10]             : '1'[0m
[1;32m==> sig-windows-2019-containerd:  -> Shared Gallery Image Version ID : '/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/image-builder-e2e-6vf1l8/providers/Microsoft.Compute/galleries/ClusterAPI1660288827fxzt/images/capi-windows-2019-containerd/versions/0.3.1660288896'[0m
[1;32m==> sig-windows-2019-containerd: 
```

```
Image Name                : 'capi-windows-2019-1660288896
``` 
is the same for both. 


On a successful build:

```
[1;32m==> sig-windows-2019-containerd:  -> Image Name                : 'capi-windows-2019-1660180017'[0m

[1;32m==> sig-windows-2019:  -> Image Name                : 'capi-windows-2019-1660180016'[0m
```
CC: @jsturtevant

**Comment by kkeshavamurthy** [comment]
Thanks for the PR @mweibel 
/lgtm
/approve

**Pull request merged**
