### PR TITLE
Update docs for 0.1.24 & include new script to handle the docs updates

### PR DESCRIPTION
**Pull request by AverageMarcus**
## Change description

* Updated docs with reference to the new `v0.1.24` release
* Introduced a new script (and make target) to make this PR easier in the future.

## Related issues

N/A

## Additional context

N/A

### CODE REVIEW

**Review by drew-viles — APPROVED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

Thanks for writing the script! Anything to make our chores simpler.

**Comment by AverageMarcus** [comment]
/unhold

Image is now published

**Pull request merged**
