### PR TITLE
Goss: Remove conditional for auditd on flatcar

### PR DESCRIPTION
**Pull request by hrak**
What this PR does / why we need it:

As auditd is now part of flatcar stable channel, the check for auditd can be enabled as mentioned in the TODO comment.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
The change looks good. cc: @invidian & team for a Flatcar perspective. 💚

**Review by invidian — COMMENTED** [review]
`auditd` service is disabled by default in Flatcar, I guess we should also make sure it's enabled during the build process?

**Comment by hrak** [comment]
> `auditd` service is disabled by default in Flatcar, I guess we should also make sure it's enabled during the build process?

i can add this if needed, looks like just removing two `when: ansible_os_family != "Flatcar"` in `images/capi/ansible/roles/node/tasks/main.yml`

**Comment by invidian** [comment]
>i can add this if needed

Please do, as CI is failing because of this right now :)

**Comment by hrak** [comment]
Done!

```
capc-cluster-md-0-8l227 ~ # systemctl status auditd.service
● auditd.service - Security Auditing Service
     Loaded: loaded (/usr/lib/systemd/system/auditd.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2023-02-03 13:50:29 UTC; 4min 30s ago
       Docs: man:auditd(8)
             https://github.com/linux-audit/audit-documentation
    Process: 1344206 ExecStart=/sbin/auditd (code=exited, status=0/SUCCESS)
    Process: 1344210 ExecStartPost=/sbin/augenrules --load (code=exited, status=0/SUCCESS)
   Main PID: 1344207 (auditd)
      Tasks: 2 (limit: 63208)
     Memory: 956.0K
        CPU: 103ms
     CGroup: /system.slice/auditd.service
             └─1344207 /sbin/auditd

Feb 03 13:50:28 capc-cluster-md-0-8l227 systemd[1]: Starting Security Auditing Service...
Feb 03 13:50:29 capc-cluster-md-0-8l227 auditd[1344207]: No plugins found, not dispatching events
Feb 03 13:50:29 capc-cluster-md-0-8l227 auditd[1344207]: Init complete, auditd 3.0.6 listening for events (startup state enable)
Feb 03 13:50:29 capc-cluster-md-0-8l227 augenrules[1344227]: No rules
Feb 03 13:50:29 capc-cluster-md-0-8l227 systemd[1]: Started Security Auditing Service.
capc-cluster-md-0-8l227 ~ # auditctl -l
-w /var/lib/containerd -p rwxa -k containerd
-w /etc/containerd -p rwxa -k containerd
-w /etc/systemd/system/containerd.service -p rwxa -k containerd
-w /etc/systemd/system/containerd.service.d -p rwxa -k containerd
-w /run/containerd -p rwxa -k containerd
-w /opt/bin/containerd-shim -p rwxa -k containerd
-w /opt/bin/containerd-shim-runc-v1 -p rwxa -k containerd
-w /opt/bin/containerd-shim-runc-v2 -p rwxa -k containerd
-w /opt/bin/runc -p rwxa -k containerd
-w /opt/bin/containerd -p rwxa -k containerd
-a never,exclude -F msgtype>=AVC -F msgtype<=1499
-a never,exclude -F msgtype=CONFIG_CHANGE
-a always,exclude -F msgtype>0
```

**Comment by invidian** [comment]
/test pull-azure-sigs

Triggering as the build is failing for me locally.

**Comment by jepio** [comment]
> Done!
> 
> ```
> ...
> -a always,exclude -F msgtype>0
> ```

This line is part of default rules Flatcar ships with (https://github.com/flatcar/coreos-overlay/blob/07a209c728b155ef1384c6e116428a5f1f427dcb/sys-process/audit/files/rules.d/99-default.rules), do you know if audit rules are first-match or will this interfere with enabling audit messages?

**Review by jepio — APPROVED** [review]
LGTM (except for that small comment about ordering of audit rules).

**Comment by invidian** [comment]
Hm, for some reason the same error occurs on CI: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_image-builder/1069/pull-azure-sigs/1622582758943494144/artifacts/azure-sigs/flatcar-gen2.log, but not locally for me on master branch.

**Comment by hrak** [comment]
> This line is part of default rules Flatcar ships with (https://github.com/flatcar/coreos-overlay/blob/07a209c728b155ef1384c6e116428a5f1f427dcb/sys-process/audit/files/rules.d/99-default.rules), do you know if audit rules are first-match or will this interfere with enabling audit messages?

What i can find is that it is first match indeed. I basically took the [existing file](https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/ansible/roles/node/files/etc/audit/rules.d/containerd.rules) and adapted the paths for Flatcar.

**Review by mboersma — COMMENTED** [review]
/lgtm

**Pull request merged**
