### PR TITLE
containerd: update to v1.6.1

### PR DESCRIPTION
**Pull request by seanschneeweiss**
What this PR does / why we need it:

Updates containerd to 1.6.0.

Release Notes: https://github.com/containerd/containerd/releases/tag/v1.6.1

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): 

**Additional context**
<sub>Sean Schneeweiss <sean.schneeweiss@mercedes-benz.com>, Daimler TSS GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)</sub>

### CODE REVIEW

**Comment by seanschneeweiss** [comment]
[0;32m    vhd-ubuntu-1804: TASK [providers : install Azure clients] ***************************************[0m
[0;32m    vhd-ubuntu-1804: fatal: [default]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip3", "install", "azure-cli"]

**Comment by seanschneeweiss** [comment]
Looks like the error is related to #766.
/retest

**Comment by codenrhoden** [comment]
@seanschneeweiss any idea what's happening with the Assets in this containerd release? It looks like all the assets on the GitHub release page are duplicated, and they have different sizes, so I can't tell which is the right one (or which one is the right checksum to validate).

**Comment by seanschneeweiss** [comment]
For Windows the following is used:
https://github.com/kubernetes-sigs/image-builder/blob/8b6dd4ae74f7bbf49941e590ab2dc1a048d67af9/images/capi/packer/config/windows/containerd.json#L3

And for Linux, e.g.:
https://github.com/kubernetes-sigs/image-builder/blob/e9fa1b2ac51e77cc5ab0db9bc52c4df61f13bbfc/images/capi/packer/qemu/packer.json#L147

**Comment by codenrhoden** [comment]
I see what I did now. I'm still not used to seeing `arm64` assets, which showed up as new with 1.6.0. I saw "arm64" and my brain changed it to "amd64". That's why I thought there were two of each. I wasn't confused at the `image-builder` side of things, I just had thought there were duplicate files at https://github.com/containerd/containerd/releases/tag/v1.6.1 (which I wouldn't have thought possible -- and indeed it is not the case). Thanks. Will take a closer look now.

**Comment by codenrhoden** [comment]
/lgtm
/approve

Thank you!

**Pull request merged**
