### PR TITLE
Use external googlecompute packer plugin

### PR DESCRIPTION
**Pull request by aslafy-z**
## Change description

Use external [googlecompute packer plugin](https://developer.hashicorp.com/packer/integrations/hashicorp/googlecompute/latest/components/builder/googlecompute).

## Related issues

- Followup https://github.com/kubernetes-sigs/image-builder/pull/1261

### CODE REVIEW

**Comment by mboersma** [comment]
/retest

The GCP job was expected to fail, see #1516. But I can see in the logs that the external plugin seems to work. 👍🏻

**Comment by mboersma** [comment]
/test pull-azure-vhds

This failure seems to be in the `main` branch, let's see if it's consistent:

```
vhd-windows-2019-containerd: FAILED. See logs in the artifacts folder.
```

**Comment by AverageMarcus** [comment]
Has there been an update to the Azure plugin thats missing some dependencies or something?

```
Installed plugin github.com/hashicorp/azure v1.4.5 in "/root/.config/packer/plugins/github.com/hashicorp/azure/packer-plugin-azure_v1.4.5_x5.0_linux_amd64"
ERROR: Error loading command module 'mysql': cannot import name 'mysql_flexibleservers' from 'azure.mgmt.rdbms' (/root/.local/lib/python3.11/site-packages/azure/mgmt/rdbms/__init__.py)
ERROR: Error loading command module 'rdbms': No module named 'azure.mgmt.rdbms.mysql_flexibleservers'
```

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
