### PR TITLE
Bump packer to 1.9.1

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
What this PR does / why we need it:
- Bump packer to 1.9.1

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by mboersma** [comment]
Thanks @Prajyot-Parab! I just want to make sure this doesn't break anything, because we don't have all possible build targets in CI, and because [v1.9.0](https://github.com/hashicorp/packer/releases/tag/v1.9.0) of packer makes several breaking changes.

In particular:
> Community-maintained plugins bundled with the Packer binary have been removed.

I think that means to support the `build-openstack-*` targets, we'll need to install that community plugin explicitly. Maybe we can do that similarly to #1209.

**Comment by Prajyot-Parab** [comment]
> Thanks @Prajyot-Parab! I just want to make sure this doesn't break anything, because we don't have all possible build targets in CI, and because [v1.9.0](https://github.com/hashicorp/packer/releases/tag/v1.9.0) of packer makes several breaking changes.
> 
> In particular:
> 
> > Community-maintained plugins bundled with the Packer binary have been removed.
> 
> I think that means to support the `build-openstack-*` targets, we'll need to install that community plugin explicitly. Maybe we can do that similarly to #1209.

Added OpenStack packer config file

**Review by mboersma — COMMENTED** [review]
/lgtm

I *think* that should cover the breaking changes, thanks!

**Comment by AverageMarcus** [comment]
/lgtm 

👍

**Review by mboersma — APPROVED** [review]
/approve

**Comment by mboersma** [comment]
/retest

```
[1;32m==> vsphere-iso.vsphere: trying key input again[0m
[1;31m==> vsphere-iso.vsphere: Error running boot command: error typing a boot command (code, down) `56, false`: ServerFaultCode: A general system error occurred: Invalid fault[0m
```

**Pull request merged**
