### PR TITLE
Add custom-post-processor block to packer ova building

### PR DESCRIPTION
**Pull request by kkeshavamurthy**
Use `custom_post_processor` & `custom_post_processor_command` variable to run custom ova image post-processing.

### CODE REVIEW

**Comment by codenrhoden** [comment]
/lgtm

@kkeshavamurthy Can you confirm that this works fine if `custom_post_processor` and `custom_post_processor_command` are completely unset? Just want to check since they don't have default values explicitly set.

**Comment by kkeshavamurthy** [comment]
Yes I checked that. Even if they are not included in the vars list, they pass.

**Comment by codenrhoden** [comment]
Thank you.

/approve

**Pull request merged**
