### PR TITLE
Update Ubuntu ISO image to 18.04.5

### PR DESCRIPTION
**Pull request by prankul88**
This is in regards to issue #387 

Have updated the ubuntu image to the newer version.

### CODE REVIEW

**Comment by randomvariable** [comment]
@prankul88 could you sign the CLA please?

**Comment by prankul88** [comment]
@randomvariable This is odd, I had signed CLA a while back :( 
Not sure about the reason why this is happening.

**Comment by randomvariable** [comment]
@prankul88 it's your commit message is signed by "ubuntu" rather than your email address. Check `git --global config user.email` and `git --global config user.name`

**Comment by hidekazuna** [comment]
@prankul88  [The Contributor License Agreement](https://github.com/kubernetes/community/blob/master/CLA.md#4-ensure-your-github-e-mail-address-matches-address-used-to-sign-cla) says use `git commit --amend --reset-author` and then `git push --force` to correct the PR.

**Comment by prankul88** [comment]
@hidekazuna Updated. Thanks for helping me out :+1:

**Comment by prankul88** [comment]
@davidewatson Can you please help to get this merged? Thanks :)

**Comment by hidekazuna** [comment]
@CecileRobertMichon Could you check this PR? We need this PR to build an image for OpenStack.

**Pull request merged**
