### PR TITLE
Update guest types for VMware Windows 2019 and 2022 OVA

### LINKED ISSUE #1544: Wrong guest OS type set for Windows Server 2022 OVA
## Environment

- **Make target:** `make _______`
- **Run using container image? (Y/N):**
- **Environment vars:**
```

```
- **Vars file:**
```

```

## What steps did you take and what happened?
The guest OS type is still set to Windows Server 2019 for 2022 OVAs.

## Relevant log output

<details>
<summary>Log Output</summary>

```
<!--
If you have any relevant build logs that could help debug this issue please include them here
but MAKE SURE ANY SENSITIVE INFO IS REMOVED!
-->
```
</details>

## Anything else you would like to add?

---

/kind bug

### PR DESCRIPTION
**Pull request by laozc**
## Change description
Update guest types for Windows Server 2019 and 2022 OVA

## Related issues
- Fixes #1544

### CODE REVIEW

**Comment by drew-viles** [comment]
Whilst it looks fine to me, I have no experience with the Windows side of things so I'm going to wing it over to @mboersma if that's ok?

**Comment by chrischdi** [comment]
/hold

In case @mboersma wants to take another look.

**Comment by chrischdi** [comment]
/hold cancel

We verified it to work, also it only affects OVA builds against vsphere :-)

**Comment by chrischdi** [comment]
It needs another approval though for `images/capi/hack/image-build-ova.py` from a top-level maintainer.

**Comment by randomvariable** [comment]
/lgtm

For top-level maintainers, those strings are from the vSphere API, and are documented here https://knowledge.broadcom.com/external/article/321876/determine-the-guest-os-from-a-vm-configu.html

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
