### PR TITLE
Clarify what belongs to the K8s node images

### PR DESCRIPTION
**Pull request by codenrhoden**
With the coming inclusion of the HAProxy image that is needed by CAPV (see #197), it makes sense to clarify in the code what is "node" related. This patch renames a bunch of Ansible related roles (and playbook) to clearly call these out as "node".

Specifically for OVAs (which are the only ones right now that will be capable of building an image other than a "node" image), we clarify the `make` targets to list "node" specifically (with "haproxy" targets coming in a later PR).

We also make a more standard pattern for the OVAs to clarify how they are built using a local vs ESX hypervisor. This will make more sense when a "vcenter" target is added in #186 .

I was preparing one big patch to add the HAProxy stuff, but I kept finding more things to cleanup and change, so thought it make sense to put this up as a separate PR. The HAProxy stuff depends on this, but that may not get filed for a couple more days still and this can go up for review now.

/assign @detiber @figo 
/cc @dims

### CODE REVIEW

**Comment by detiber** [comment]
/lgtm
/hold for additional reviews

feel free to remove the hold whenever

**Comment by codenrhoden** [comment]
I'm going to keep holding on this one until after I get #186 merged in (which I'm testing now), in order to reduce the re-base burden on that contributor. :)

**Comment by codenrhoden** [comment]
/hold cancel
@detiber Okay, now that the vSphere builder is merged in, this is ready for re-review!

**Pull request merged**
