### PR TITLE
Update containerd to 1.6.22

### PR DESCRIPTION
**Pull request by hrak**
What this PR does / why we need it:

Update containerd to 1.6.22

Changes [can be found here](https://github.com/containerd/containerd/releases/tag/v1.6.22)

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by hrak** [comment]
Question: should we consider switching to containerd 1.7 in the near future?

**Comment by mboersma** [comment]
/ok-to-test

> should we consider switching to containerd 1.7 in the near future?

Generally we should try to keep critical packages like that fresh, so I'd say yes. But IDK if there are specific migration issues or if 1.7 is problematic for any particular provider (chances are good it breaks *something*, right?).

Unless someone has a specific objection, I think we should try 1.7 soon.

**Review by mboersma — COMMENTED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/approve

I opened #1244 to track updating to containerd v1.7.

**Pull request merged**
