### PR TITLE
Pin Azure windows-2019 to known working version

### PR DESCRIPTION
**Pull request by mboersma**
## Change description

Changes the windows-2019 build image to a known working version.

## Related issues

- Refs #1602

## Additional context

How to browse the relevant base images:

```shell
az vm image list \
  --publisher MicrosoftWindowsServer \
  --offer WindowsServer \
  --sku 2019-datacenter-core-smalldisk \
  --all
```

### CODE REVIEW

**Comment by mboersma** [comment]
This passed CI for the build-azure-*-windows-2019 jobs. I'll remove the TEMP commit.

- [pull-azure-sigs](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_image-builder/1615/pull-azure-sigs/1848202586239275008)
- [pull-azure-vhds](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_image-builder/1615/pull-azure-vhds/1848202586167971840)

**Comment by mboersma** [comment]
I used this to build community gallery images that got kubernetes-sigs/cluster-api-provider-azure#5167 unstuck, so I'm confident this is a functional workaround.

**Comment by jsturtevant** [comment]
/lgtm
/approve

We can unpin once November patches come out.  Hopefully it will be resolved then

**Pull request merged**
