### PR TITLE
Load packer goss plugin via config file

### PR DESCRIPTION
**Pull request by aslafy-z**
## Change description

Move from `hack/ensure-goss.sh` to `config.pkr.hcl` common packer configuration file.

## Additional informations

This PR includes a bump from 3.1.4 to the latest 3.x release (currently [3.2.12](https://github.com/YaleUniversity/packer-plugin-goss/releases/tag/v3.2.12)).

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm

This seems cleaner and simpler. Thank you!

/assign @AverageMarcus @drew-viles

**Review by drew-viles — COMMENTED** [review]
Nice! /approve

**Pull request merged**
