### PR TITLE
start and enable `networkd-dispatcher` during proxmox build

### LINKED ISSUE #1562: Failes to build proxmox-ubuntu-2404 -
## Environment

- **Make target:** `make build-proxmox-ubuntu-2404`
- **Run using container image? (Y/N):** N
- **Environment vars:**
```
export PROXMOX_URL="https://10.10.10.200:8006/api2/json"
export PROXMOX_USERNAME=USER@pam!TAG
export PROXMOX_TOKEN=TOKEN
export PROXMOX_NODE="pve1"
export PROXMOX_ISO_POOL="local"
export PROXMOX_BRIDGE="vmbr0"
export PROXMOX_STORAGE_POOL="local-lvm"
```
- **Vars file:**
```

```

## What steps did you take and what happened?

1. export env vars
2. run `make build-proxmox-ubuntu-2404`
3. get check error `Service: networkd-dispatcher: running:\nExpected\n    \u003cbool\u003e: false\nto equal\n    \u003cbool\u003e: true`

## What did you expect to happen?

Successful creation of a template on my Proxmox host

## Relevant log output

<details>
<summary>Log Output</summary>

[log.txt](https://github.com/user-attachments/files/16907995/log.txt)

</details>

## Anything else you would like to add?
Same problem when using the provided packer version.

---

/kind bug

### PR DESCRIPTION
**Pull request by nilsherzig**
## Change description

Fix to #1562 - otherwise the build process / tests will fail.

## Related issues

- Fixes #1562

### CODE REVIEW

**Comment by AverageMarcus** [comment]
/ok-to-test

Thanks @nilsherzig ! Would you mind signing the CLA so we can accept this PR please? 😄

**Comment by AverageMarcus** [comment]
Also, I think you might need to remove the backticks from the commit message (they can remain in the PR title though)

**Comment by nilsherzig** [comment]
Thanks, CLA is signed and backticks are removed :)

**Pull request merged**
