### PR TITLE
Update the test cloud-init data for current CAPI

### PR DESCRIPTION
**Pull request by akutz**
This patch updates the cloud-init data used for testing the machine images to match the data generated by Cluster API v1alpha2.

/kind feature

cc @codenrhoden @figo

### CODE REVIEW

**Comment by akutz** [comment]
Hi @figo / @codenrhoden,

Could one of you please take a look at this? Thanks!

**Comment by codenrhoden** [comment]
/lgtm

@akutz, since this is all sample data, there would be no need to regenerate older images, correct?

**Comment by akutz** [comment]
Correct.

**Pull request merged**
