### PR TITLE
Install nfs-common package for Azure image

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

What this PR does / why we need it:
Azure image installs netbase and nfs-common package.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

related: https://github.com/kubernetes/test-infra/issues/24957

### CODE REVIEW

**Comment by jsturtevant** [comment]
My understanding this is required for some of the features in the Azure cloudprovider, specifically for some e2e tests around functionality.  We discussed it briefly but maybe @lzhecheng can expand upon what features this enabled in the cloudprovider.

**Comment by jsturtevant** [comment]
As a stop gap we are adding it to the pre-kubeadm commands in capz: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2158.

**Comment by CecileRobertMichon** [comment]
@codenrhoden my understanding is that it's required to pass full k8s conformance on Azure (see https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2158#issuecomment-1064670635). I guess it depends if we want to be able to say image-builder as producing k8s conformant images or not. If so I would lean towards including it.

@lzhecheng can you please clarify if users would require this package to be installed outside of conformance tests?

**Comment by lzhecheng** [comment]
@CecileRobertMichon thank you for the explanation!

@codenrhoden so far I only see it needed for some conformance tests: "should access to two volumes with the same volume mode and retain data across pod recreation on the same node". I think we need to include nfs-common into image or update those tests to skip on nodes without the package.

**Comment by codenrhoden** [comment]
> I guess it depends if we want to be able to say image-builder as producing k8s conformant images or not. If so I would lean towards including it.

@CecileRobertMichon I think that's definitely what we want to say, so I agree. Thanks for the discussion!

/hold cancel
/lgtm

**Comment by kkeshavamurthy** [comment]
@lzhecheng pls rebase. #831 should fix the failing ova tests

**Comment by lzhecheng** [comment]
@kkeshavamurthy I have updated the PR. Thank you!

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Pull request merged**
