### PR TITLE
Bump ansible-core to v2.15.10

### PR DESCRIPTION
**Pull request by mboersma**
What this PR does / why we need it:

Updates `ansible-core` to version [v2.15.10](https://github.com/ansible/ansible/releases/tag/v2.15.10). Maintains compatibility with python 3.9.

Which issue(s) this PR fixes: 

N/A

**Additional context**

### CODE REVIEW

**Comment by drew-viles** [comment]
Yeah it's feeling poorly

image

**Review by drew-viles — APPROVED** [review]
Once galaxy is up I'm sure all is going to be well!

**Comment by AverageMarcus** [comment]
Looks like we have an issue with Photon 4. I'm seeing the same in my PR https://github.com/kubernetes-sigs/image-builder/pull/1438#issuecomment-2042426202

Looks like there's problems with some packages:
```
Error verifying signature of: /var/cache/tdnf/photon-updates/rpms/x86_64/linux-5.10.212-4.ph4.x86_64.rpm\nError processing package: x86_64/linux-5.10.212-4.ph4.x86_64.rpm\nError(1514) : RPM is signed but failed to match with known keys. Use --nogpgcheck to ignore.
```

**Comment by mboersma** [comment]
/retest

Hoping #1443 fixes the CI issue.

**Pull request merged**
