### PR TITLE
Update containerd to 1.7.10

### PR DESCRIPTION
**Pull request by hrak**
What this PR does / why we need it:

This PR updates containerd to 1.7.10

Release notes: https://github.com/containerd/containerd/releases/tag/v1.7.10

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by mboersma** [comment]
Thanks @hrak!

When I did #1303, I noticed containerd is also installed for the `ppc64le` architecture here: https://github.com/kubernetes-sigs/image-builder/blob/b3a662fc426cfa4deecfc81b892aecbf0e140f7a/images/capi/packer/config/ppc64le/containerd.json#L1-L5

Would you mind updating that as well?

**Comment by hrak** [comment]
> Thanks @hrak!
> 
> When I did #1303, I noticed containerd is also installed for the `ppc64le` architecture here:
> 
> https://github.com/kubernetes-sigs/image-builder/blob/b3a662fc426cfa4deecfc81b892aecbf0e140f7a/images/capi/packer/config/ppc64le/containerd.json#L1-L5
> 
> Would you mind updating that as well?

No problem, done!

**Review by mboersma — COMMENTED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
