### PR TITLE
Update Ubuntu 22.04 ISO URLs to use latest stable URLs

### PR DESCRIPTION
**Pull request by AverageMarcus**
## Change description

This updates all the Ubuntu 22.04 ISO URLs to point to the latest available version using an URL that wont break when a new release is available.

Updated 22.04 to latest: `22.04.5`

## Related issues

- https://github.com/kubernetes-sigs/image-builder/issues/1334

## Additional context

I haven't updated the Ubuntu 20.04 ISO urls as they would also require changes away from the legacy server images.

I haven't updated [qemu-ubuntu-2304.json](https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/packer/qemu/qemu-ubuntu-2304.json) as currently the release is beta as far as I can tell and doesn't yet have the stable URLs available.

### CODE REVIEW

**Comment by AverageMarcus** [comment]
Failed on Proton 🤨  

/test pull-ova-all

**Review by mboersma — APPROVED** [review]
/lgtm

**Comment by drew-viles** [comment]
/approve

I'm on vacation/holiday at the moment so may be delayed responding to things.

**Comment by AverageMarcus** [comment]
Sorry, I had to force-push (with no changes) to unblock a stuck GitHub check. Could I please get a `/lgtm` again? 🙏

**Pull request merged**
