### PR TITLE
Add ubuntu 22.04 for outscale

### PR DESCRIPTION
**Pull request by outscale-vbr**
What this PR does / why we need it:
Add ubuntu 22.04 for outscale

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Comment by outscale-vbr** [comment]
@mboersma @jsturtevant Thanks you :)

**Pull request merged**
