### PR TITLE
photon: Break out reboot into separate shell provisioner step.

### PR DESCRIPTION
**Pull request by randomvariable**
When using Packer, Ansible roles should not include the reboot command.
This is because Packer controls the SSH connection, and has no indication
that the machine will be rebooted - the SSH connection is reset and no
attempt to reconnect is made, causing Packer to hang.
This can be obviated with some timing-dependent hacks (which will work with
varying levels of success across different infrastructures), but
here instead, we create a specific firstboot playbook, and insert a
shell provisioner step to reboot the machine using the "expect_disconnect"
flag to inform Packer that the machine will disconnect and it can move
on to the next provisioner.

### CODE REVIEW

**Comment by voor** [comment]
Should there be some kind of conditional to avoid the unnecessary reboot for other OS types?

**Comment by randomvariable** [comment]
> Should there be some kind of conditional to avoid the unnecessary reboot for other OS types?
There's no syntax to make a provisioner conditional, and adding ~30s for the other OS seems like a reasonable compromise.

**Comment by voor** [comment]
> > Should there be some kind of conditional to avoid the unnecessary reboot for other OS types?
> 
> There's no syntax to make a provisioner conditional, and adding ~30s for the other OS seems like a reasonable compromise.

Here's an example with the AMI packer builds: https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/ami/packer.json#L108-L112

**Comment by randomvariable** [comment]
Thanks @voor . Have updated.

**Comment by randomvariable** [comment]
Any update on this @figo ? PhotonOS builds are basically broken for most users.

**Comment by figo** [comment]
> Any update on this @figo ? PhotonOS builds are basically broken for most users.

@randomvariable I don't have much context about this issue, what specific action are you expecting from me?

**Comment by randomvariable** [comment]
We could do with it being merged as most Photon builds on vSphere halt without it.

**Comment by EleanorRigby** [comment]
Taking a look.

**Comment by EleanorRigby** [comment]
okay, this works. Tried Photon and CentOS. Does the breakaway reboot task only for Photon.

Photon OS includes firstboot task
```
 vmware-iso:
    vmware-iso: TASK [include_role : firstboot] ************************************************
    vmware-iso:
    vmware-iso: TASK [firstboot : include_tasks] ***********************************************
    vmware-iso: included: /Users/taggarwal/workspace/eleanor/image-builder/images/capi/ansible/roles/firstboot/tasks/photon.yml for default
    vmware-iso:
    vmware-iso: TASK [firstboot : Perform a tdnf distro-sync] **********************************
    vmware-iso: changed: [default]
```
and builds successfully
```
    vmware-iso (shell-local): image-post-create-config: create snapshot 'new'
    vmware-iso (shell-local): image-post-create-config: update cpu count to 2
    vmware-iso (shell-local): image-post-create-config: create snapshot '2cpu'
    vmware-iso (shell-local): image-post-create-config: insert cloud-init data
    vmware-iso (shell-local): image-post-create-config: create snapshot 'cloudinit'
Build 'vmware-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> vmware-iso: VM files in directory: ./output/photon-3-kube-v1.16.14
--> vmware-iso:
--> vmware-iso:
```

CentOS skips first boot task 
```
vmware-iso: TASK [include_role : firstboot] ************************************************
    vmware-iso:
    vmware-iso: TASK [firstboot : include_tasks] ***********************************************
    vmware-iso: skipping: [default]
    vmware-iso:
```
and builds successfully
```
    vmware-iso (shell-local): image-post-create-config: insert cloud-init data
    vmware-iso (shell-local): image-post-create-config: create snapshot 'cloudinit'
Build 'vmware-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> vmware-iso: VM files in directory: ./output/centos-7-kube-v1.16.14
--> vmware-iso:
--> vmware-iso:
```

**Pull request merged**
