### PR TITLE
Update ppc64le containerd version to v1.6.19

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
What this PR does / why we need it:
- Update containerd version to v1.6.19

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by mboersma** [comment]
/lgtm
/retitle Update ppc64le containerd version to v1.6.19

**Pull request merged**
