### PR TITLE
Run ansible-lint --fix

### PR DESCRIPTION
**Pull request by AverageMarcus**
What this PR does / why we need it:

This is the result of running `make lint-fix` followed by `make lint-ignore` to auto-fix all that are possible by `ansible-lint`.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Review by drew-viles — APPROVED** [review]
Seeing 105 files changed, 749 changes and 899 deletions is always daunting at first 💀 

However I see what it's done and it's rather logical we get those new calls in to ansible components as well as all the adjustments around replacing single quotes and removing doubles where required.

Ran a build my side and looks good.

**Comment by AverageMarcus** [comment]
Haha! Yeah I was pretty scared with the amount of changes it generated 😆  I'm hoping there's nothing dangerous in there. I don't think there is from what I can tell but I'm not 100% certain.

This PR will now make it look like I've touched most of the codebase so I'm looking forward to people asking me about things I don't know in the future because my name is against a specific line of code 🤣

**Comment by AverageMarcus** [comment]
Ugh! Looks like this isn't going to be as easy as I hoped 😞  

I'm going to close this for now until I have more time to look at it.

**Comment by AverageMarcus** [comment]
> We could tailor this to new contributors as well, by splitting it into several good_first_issue issues and describing specifically how to run the linter with --fix and then make lint-ignore. What do you think?

Yeah I like this (and see you've started with it already 🎉 ).

Sorry for the delayed response. Struggled with time this week. 😅

**Pull request closed without merging**
