### PR TITLE
Use ssh-extra-args param

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
What this PR does / why we need it:
- This will fix the powervs image build related issues

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm

**Review by AverageMarcus — COMMENTED** [review]
/lgtm 
/approve

**Pull request merged**
