### PR TITLE
Add OWNERS file to images/capi

### PR DESCRIPTION
**Pull request by vincepri**
Adds the Cluster API admins as approvers to the subfolder

### CODE REVIEW

**Comment by vincepri** [comment]
How do you mean? I’m not sure if we can reference groups across repos

**Comment by timothysc** [comment]
Add the alias to the main OWNERS_ALIAS to the root of this repo, and then in this specific OWNERS file just reference this alias.

**Comment by vincepri** [comment]
Sure I can try that

**Comment by vincepri** [comment]
@timothysc Done, ptal

**Comment by codenrhoden** [comment]
Could be a follow-on to this, but I'm wondering if @figo and myself should be moved from the top level `OWNERS` to this new one at `images/capi` instead. I know for myself, that's the only area I have knowledge and interest in.

**Comment by timothysc** [comment]
@codenrhoden knock on PR ;-) 
/lgtm

**Pull request merged**
