### PR TITLE
Update to Rocky Linux 8.6

### PR DESCRIPTION
**Pull request by Pearl1594**
What this PR does / why we need it:

The PR updates Rocky Linux ISO to the latest version - 8.6 

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by kkeshavamurthy** [comment]
If an 8.6 AMI is available, can we bump that as well pls?

**Comment by codenrhoden** [comment]
> If an 8.6 AMI is available, can we bump that as well pls?

@kkeshavamurthy I just tried out if there was an 8.6 available, but it doesn't look like it:

```
--> rockylinux-8: No AMI was found matching filters: {
  Filters: [
    {
      Name: "name",
      Values: ["Rocky-8-ec2-8.6-*"]
```

I think we should just pull this in as-is.

**Pull request merged**
