### PR TITLE
Fix regression in Flatcar provisioner

### PR DESCRIPTION
**Pull request by johananl**
What this PR does / why we need it:

In #883 I've accidentally introduced a regression which seems to have broken the AMI, QEMU and raw Flatcar builds (other distros weren't affected).

Turns out that removing the `BUILD_NAME` assignment inside `execute_command` was a mistake because variables defined within `environment_vars` don't affect `execute_command`, which made `if [[ \"${BUILD_NAME}\" == *\"flatcar\"* ]]` always evaluate to false.

Therefore, we first revert 4fb09d311a139aa67ded9c7cdcc3f8d35bd50c07 to fix the build.

Now, we are left with two "layers" of conditionals: Inside `execute_command` and inside `bootstrap-flatcar.sh` Even though I initially thought it'd be good to keep the `if` inside `bootstrap-flatcar.sh` as a failsafe, I no longer think so, hence the 2nd commit. See the commit message for a rationale.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): None

**Additional context**
To test this PR, ensure the following builds pass:

```
make build-qemu-flatcar
make build-qemu-ubuntu-1804
```

### CODE REVIEW

**Comment by johananl** [comment]
cc @kkeshavamurthy

**Comment by johananl** [comment]
I'm still running manual tests. Will mark as ready for review when done.

**Comment by johananl** [comment]
> I'm still running manual tests. Will mark as ready for review when done.

Done. Upon my testing both Flatcar and Ubuntu QEMU builds are passing now.

**Comment by kkeshavamurthy** [comment]
Thanks @johananl 
Did you run any of the non-flatcar images and make sure nothing was broken, just to make sure?

**Comment by johananl** [comment]
> Thanks @johananl Did you run any of the non-flatcar images and make sure nothing was broken, just to make sure?

Yes, as I wrote above I tested Ubuntu, too 🙂
Do you think we should check anything else? I could of course test all distros, however I didn't want to delay the fix further.

**Comment by johananl** [comment]
As a side note, I think it would be good to rely on the CI to test all platforms regularly (see https://github.com/kubernetes-sigs/image-builder/issues/881).

**Comment by kkeshavamurthy** [comment]
I missed Ubuntu :)
Yeah I had done some initial work around getting AWS creds for having CI. It got tossed around a while in k8s/test-infra and then I lost interest. I need to join the k8s infra meeting and try to get the creds again. Let me know if you are interested in looking into it further and I'll give you more context, it would be very helpful. I think 75% of the work is done.

**Pull request merged**
