### PR TITLE
outscale: user can make OMI publicly accessible or not

### PR DESCRIPTION
**Pull request by pli01**
## Change description

On outscale, user can choose to make OMI publicly accessible or not
Default: publicly accessible

## Related issues

- Fixes #

### CODE REVIEW

**Comment by AverageMarcus** [comment]
Just so I'm clear - what does "publicly accessible" mean in this context? I'm wondering if `true` is still a sensible default or not?

**Comment by pli01** [comment]
> Just so I'm clear - what does "publicly accessible" mean in this context? I'm wondering if `true` is still a sensible default or not?
> 
> Especially as the property being updated is called `global_permission`.

I agree with you

This option should be "false" by default, to not publish the image publicly outside the "tenant"
Sharing the image publicly should be enabled voluntarily.

On Outscale, an image can have:
- a private visibility to the "tenant" only
- or "publicly available" and visible to all cloud users, to all tenants

https://developer.hashicorp.com/packer/integrations/outscale/outscale/latest/components/builder/bsu

**Comment by AverageMarcus** [comment]
@mboersma What do you think about changing this default to `false`?

/cc @vincentBaer for your input too as you did a lot of the previous work on this provider I think :)

**Comment by outscale-hmi** [comment]
Hello 
thanks @pli01 for the contribution
@AverageMarcus I agree with these changes, as they provide the flexibility to make images public based on the client's input, while still defaulting to true to ensure accessibility when no specific value is provided which is our initial default value chosen.

**Review by AverageMarcus — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
