### PR TITLE
Bump ansible-core to v2.15.3

### PR DESCRIPTION
**Pull request by mboersma**
/kind cleanup

## Change description

Updates `ansible-core` to [v2.15.13](https://pypi.org/project/ansible-core/2.15.13/), still keeping compatibility with Python 3.9.

## Related issues

N/A

### CODE REVIEW

**Comment by mboersma** [comment]
/retest

#1654 isn't reproducible for me locally. Maybe it's been fixed upstream by Canonical?

**Comment by mboersma** [comment]
/test pull-azure-sigs

I've seen this auth flake before, not sure what to do about it. Looks like the other Ubuntu 22.04 problem was transient. 🙌🏻

**Comment by drew-viles** [comment]
With that in mind then

/lgtm

**Comment by mboersma** [comment]
@drew-viles the flake isn't something I plan to fix because it's been exceedingly rare, but I will create an issue to track it. Please approve whenever time permits, thanks!

**Pull request merged**
