### PR TITLE
Add tutorial to the documentation gitbook for building/deploying images on vSphere and AWS

### PR DESCRIPTION
**Pull request by moondev**
This tutorial outlines building a machine image, as well as details for how to reference the resulting vSphere/AWS image artifact inside the cluster manifests.

I placed the markdown in `docs/book/src/tutorials` and updated the menu tree in `SUMMARY.md`. If there  is a better place for this please share!

The tutorial directs the reader to use commit `1f9002a`, ideally this should be changed to a tagged release when ready.   Thanks!

### CODE REVIEW

**Comment by moshloop** [comment]
Could we split this into 2 pages? 1 for AWS and another for vSphere ?

**Comment by moondev** [comment]
Sure thing @moshloop I will create a separate page for each. I agree this will scale better as new provider guides are added.

**Comment by moondev** [comment]
Quick update on this, i'm working on updates this week to a refined version of these docs and will update this PR accordingly (as well as splitting to separate page per provider).

**Comment by codenrhoden** [comment]
@moondev Any progress on this one?

**Comment by moondev** [comment]
Update: @codenrhoden will take this over from here, thank you!

**Pull request closed without merging**
