### PR TITLE
Fix Flatcar detection in node role

### LINKED ISSUE #969: Flatcar OS detection failure
**What steps did you take and what happened:**

```
$ make FLATCAR_CHANNEL=stable FLATCAR_VERSION=3227.2.2 build-qemu-flatcar

...

    qemu: TASK [node : Copy etcd network tuning script] **********************************
    qemu: fatal: [default]: FAILED! => {"changed": false, "checksum": "38b8f0b3ba1cfc04bc8d6cdafd7f141a0fef6e61", "msg": "Destination /usr/local/bin not writable"}
    qemu:
    qemu: PLAY RECAP *********************************************************************
    qemu: default                    : ok=9    changed=5    unreachable=0    failed=1    skipped=126  rescued=0    ignored=0
    qemu:
==> qemu: Provisioning step had errors: Running the cleanup provisioner, if present...
==> qemu: Deleting output directory...
Build 'qemu' errored after 5 minutes 51 seconds: Error executing Ansible: Non-zero exit status: exit status 2
```

**What did you expect to happen:**

Build an image.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

It is because of this line in `images/capi/ansible/roles/node/defaults/main.yml`

```
external_binary_path: "{{ '/opt/bin' if ansible_os_family == 'Flatcar' else '/usr/local/bin' }}"
```

It doesn't detect Flatcar correctly.

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
- Packer Version:
- Packer Provider:
- Ansible Version: 
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug

### PR DESCRIPTION
**Pull request by kopiczko**
What this PR does / why we need it:

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #969

**Additional context**
Possibly there is a better place to put that. This detection is already happening in:

* `images/capi/ansible/roles/setup/tasks/bootstrap-flatcar.yml`
* `images/capi/ansible/roles/setup/tasks/main.yml`

### CODE REVIEW

**Review by AverageMarcus — APPROVED** [review]

**Comment by AverageMarcus** [comment]
Looks good, also doesn't hurt to have it in when the value is correctly reported :)

**Comment by johananl** [comment]
I'm a bit confused as to why I haven't encountered this problem yet as I've been building Flatcar images regularly for the past couple of months. What has changed? Alternatively, under which conditions is the bug triggered?

**Comment by johananl** [comment]
BTW, a fix for the root cause has been merged upstream today: https://github.com/ansible/ansible/pull/77635 Might take a while until it's released though.

**Comment by kopiczko** [comment]
For `pull-azure-vhds` check, the errors don't seem to be related:

From https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_image-builder/970/pull-azure-vhds/1567845942558724096

```
vhd-centos-7: SUCCESS
vhd-ubuntu-1804: FAILED. See logs in the artifacts folder.
vhd-windows-2019: SUCCESS
vhd-ubuntu-2004: FAILED. See logs in the artifacts folder.
vhd-windows-2022-containerd: SUCCESS
vhd-windows-2019-containerd: SUCCESS
+ EXIT_VALUE=1
```

## vhd-ubuntu-2004

From https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_image-builder/970/pull-azure-vhds/1567845942558724096/artifacts/azure-vhds/ubuntu-2004.log

```
[0;32m    vhd-ubuntu-2004: TASK [providers : Install iptables persistence] ********************************[0m
[0;32m    vhd-ubuntu-2004: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Connection to 127.0.0.1 closed.[0m
[0;32m    vhd-ubuntu-2004: fatal: [default]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/.ansible/ansible-tmp-1662639241.0854626-3203-24285323348670/AnsiballZ_apt.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/tmp/.ansible/ansible-tmp-1662639241.0854626-3203-24285323348670/AnsiballZ_apt.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/.ansible/ansible-tmp-1662639241.0854626-3203-24285323348670/AnsiballZ_apt.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.apt', init_globals=dict(_module_fqn='ansible.modules.apt', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_apt_payload_y4a95202/ansible_apt_payload.zip/ansible/modules/apt.py\", line 327, in <module>\n  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 655, in _load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 618, in _load_backward_compatible\n  File \"<frozen zipimport>\", line 259, in load_module\n  File \"/tmp/ansible_apt_payload_y4a95202/ansible_apt_payload.zip/ansible/module_utils/urls.py\", line 115, in <module>\n  File \"/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py\", line 46, in <module>\n    import OpenSSL.SSL\n  File \"/usr/lib/python3/dist-packages/OpenSSL/__init__.py\", line 8, in <module>\n    from OpenSSL import crypto, SSL\n  File \"/usr/lib/python3/dist-packages/OpenSSL/crypto.py\", line 1553, in <module>\n    class X509StoreFlags(object):\n  File \"/usr/lib/python3/dist-packages/OpenSSL/crypto.py\", line 1573, in X509StoreFlags\n    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK\nAttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'\nError in sys.excepthook:\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/apport_python_hook.py\", line 72, in apport_excepthook\n    from apport.fileutils import likely_packaged, get_recent_crashes\n  File \"/usr/lib/python3/dist-packages/apport/__init__.py\", line 5, in <module>\n    from apport.report import Report\n  File \"/usr/lib/python3/dist-packages/apport/report.py\", line 32, in <module>\n    import apport.fileutils\n  File \"/usr/lib/python3/dist-packages/apport/fileutils.py\", line 12, in <module>\n    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket\n  File \"/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py\", line 1, in <module>\n    import requests\n  File \"/usr/lib/python3/dist-packages/requests/__init__.py\", line 95, in <module>\n    from urllib3.contrib import pyopenssl\n  File \"/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py\", line 46, in <module>\n    import OpenSSL.SSL\n  File \"/usr/lib/python3/dist-packages/OpenSSL/__init__.py\", line 8, in <module>\n    from OpenSSL import crypto, SSL\n  File \"/usr/lib/python3/dist-packages/OpenSSL/crypto.py\", line 1553, in <module>\n    class X509StoreFlags(object):\n  File \"/usr/lib/python3/dist-packages/OpenSSL/crypto.py\", line 1573, in X509StoreFlags\n    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK\nAttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'\n\nOriginal exception was:\nTraceback (most recent call last):\n  File \"/tmp/.ansible/ansible-tmp-1662639241.0854626-3203-24285323348670/AnsiballZ_apt.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/tmp/.ansible/ansible-tmp-1662639241.0854626-3203-24285323348670/AnsiballZ_apt.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/.ansible/ansible-tmp-1662639241.0854626-3203-24285323348670/AnsiballZ_apt.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.apt', init_globals=dict(_module_fqn='ansible.modules.apt', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_apt_payload_y4a95202/ansible_apt_payload.zip/ansible/modules/apt.py\", line 327, in <module>\n  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 655, in _load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 618, in _load_backward_compatible\n  File \"<frozen zipimport>\", line 259, in load_module\n  File \"/tmp/ansible_apt_payload_y4a95202/ansible_apt_payload.zip/ansible/module_utils/urls.py\", line 115, in <module>\n  File \"/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py\", line 46, in <module>\n    import OpenSSL.SSL\n  File \"/usr/lib/python3/dist-packages/OpenSSL/__init__.py\", line 8, in <module>\n    from OpenSSL import crypto, SSL\n  File \"/usr/lib/python3/dist-packages/OpenSSL/crypto.py\", line 1553, in <module>\n    class X509StoreFlags(object):\n  File \"/usr/lib/python3/dist-packages/OpenSSL/crypto.py\", line 1573, in X509StoreFlags\n    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK\nAttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'\nConnection to 127.0.0.1 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}[0m
```

Unescaped:

```
Traceback (most recent call last):
  File "/tmp/.ansible/ansible-tmp-1662639241.0854626-3203-24285323348670/AnsiballZ_apt.py", line 100, in <module>
    _ansiballz_main()
  File "/tmp/.ansible/ansible-tmp-1662639241.0854626-3203-24285323348670/AnsiballZ_apt.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/.ansible/ansible-tmp-1662639241.0854626-3203-24285323348670/AnsiballZ_apt.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.apt', init_globals=dict(_module_fqn='ansible.modules.apt', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_apt_payload_y4a95202/ansible_apt_payload.zip/ansible/modules/apt.py", line 327, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/ansible_apt_payload_y4a95202/ansible_apt_payload.zip/ansible/module_utils/urls.py", line 115, in <module>
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Original exception was:
Traceback (most recent call last):
  File "/tmp/.ansible/ansible-tmp-1662639241.0854626-3203-24285323348670/AnsiballZ_apt.py", line 100, in <module>
    _ansiballz_main()
  File "/tmp/.ansible/ansible-tmp-1662639241.0854626-3203-24285323348670/AnsiballZ_apt.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/.ansible/ansible-tmp-1662639241.0854626-3203-24285323348670/AnsiballZ_apt.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.apt', init_globals=dict(_module_fqn='ansible.modules.apt', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_apt_payload_y4a95202/ansible_apt_payload.zip/ansible/modules/apt.py", line 327, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/ansible_apt_payload_y4a95202/ansible_apt_payload.zip/ansible/module_utils/urls.py", line 115, in <module>
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
Connection to 127.0.0.1 closed.
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error
```

## vhd-ubuntu-1804

From https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_image-builder/970/pull-azure-vhds/1567845942558724096/artifacts/azure-vhds/ubuntu-1804.log

```
[0;32m    vhd-ubuntu-1804: TASK [providers : Install iptables persistence] ********************************[0m
[0;32m    vhd-ubuntu-1804: fatal: [default]: FAILED! => {"changed": false, "module_stderr": "/usr/lib/python3/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.\n  from cryptography import x509\nTraceback (most recent call last):\n  File \"<stdin>\", line 16, in <module>\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_apt_payload_H6xg61/ansible_apt_payload.zip/ansible/modules/apt.py\", line 327, in <module>\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 656, in _load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 626, in _load_backward_compatible\n  File \"/tmp/ansible_apt_payload_H6xg61/ansible_apt_payload.zip/ansible/module_utils/urls.py\", line 115, in <module>\n  File \"/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py\", line 46, in <module>\n    import OpenSSL.SSL\n  File \"/usr/lib/python3/dist-packages/OpenSSL/__init__.py\", line 8, in <module>\n    from OpenSSL import crypto, SSL\n  File \"/usr/lib/python3/dist-packages/OpenSSL/crypto.py\", line 1550, in <module>\n    class X509StoreFlags(object):\n  File \"/usr/lib/python3/dist-packages/OpenSSL/crypto.py\", line 1570, in X509StoreFlags\n    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK\nAttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'\nConnection to 127.0.0.1 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}[0m
```

Unescaped:

```
/usr/lib/python3/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography import x509
Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_apt_payload_H6xg61/ansible_apt_payload.zip/ansible/modules/apt.py", line 327, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/tmp/ansible_apt_payload_H6xg61/ansible_apt_payload.zip/ansible/module_utils/urls.py", line 115, in <module>
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1550, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1570, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
Connection to 127.0.0.1 closed.
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error
```

**Comment by kopiczko** [comment]
> I'm a bit confused as to why I haven't encountered this problem yet as I've been building Flatcar images regularly for the past couple of months. What has changed? Alternatively, under which conditions is the bug triggered?

No idea, I was building it a few weeks ago and now it fails.

This is my full command:

```
make PACKER_VAR_FILES=packer/qemu/pawel.local.json FLATCAR_CHANNEL=stable FLATCAR_VERSION=3227.2.2 OEM_ID="openstack" build-qemu-flatcar
```

```
$ cat packer/qemu/pawel.local.json
{
  "accelerator": "hvf",
  "kubernetes_semver": "v1.22.9"
}
```

I'm not sure if we need to care too much when your fix to ansible is merged and it is released all of that is going to be removed anyway.

**Comment by johananl** [comment]
@kopiczko Alright, I can reproduce the problem, too.

As for why we need to do the workaround twice - I think `set_fact` within a role sets the fact *for that role*.
If this isn't a lot of work, I'd try to find a way to do the workaround once globally.

Also, looks like we have some duplication in the way we handle the bin path, too:

https://github.com/kubernetes-sigs/image-builder/blob/2e8425182a9e1894915f621c508d1ba9c7900091/images/capi/ansible/roles/node/defaults/main.yml#L110

https://github.com/kubernetes-sigs/image-builder/blob/2e8425182a9e1894915f621c508d1ba9c7900091/images/capi/ansible/roles/setup/tasks/bootstrap-flatcar.yml#L13-L17

Do you think we can consolidate the two?

**Comment by jsturtevant** [comment]
> For `pull-azure-vhds` check, the errors don't seem to be related:

This is being fixed in https://github.com/kubernetes-sigs/image-builder/pull/968

**Comment by kopiczko** [comment]
@johananl aligned, check ccc7c2fdcacecb63b56e37995bf0ce46a9f879c5

**Review by johananl — APPROVED** [review]

**Pull request merged**
