### PR TITLE
Add more OCI builder properties

### PR DESCRIPTION
**Pull request by kkeshavamurthy**
What this PR does / why we need it:
Added a few more oci builder properties that would be useful for image-building. 

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by kkeshavamurthy** [comment]
@mkumatag 
PTAL

**Comment by mkumatag** [comment]
overall lgtm but need another pair of eyes.
/lgtm
/hold

**Comment by kkeshavamurthy** [comment]
Thanks @mkumatag  @SanikaGawhane

**Pull request merged**
