### PR TITLE
fixes for generating azure gen2 images

### PR DESCRIPTION
**Pull request by nader-ziada**
What this PR does / why we need it:
- some fixes to enable generation of azure gen 2 images

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by nader-ziada** [comment]
any thoughts on this?

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/assign @mboersma

**Review by mboersma — APPROVED** [review]
lgtm

**Pull request merged**
