### PR TITLE
Add Ubuntu 22.04 LTS for Azure

### PR DESCRIPTION
**Pull request by mboersma**
What this PR does / why we need it:

Adds Ubuntu 22.04 LTS build support to Azure.

Which issue(s) this PR fixes:

Refs #960

**Additional context**:

I've tested this and it builds successfully in our DevOps pipeline, but the resulting images need to be tested in a Kubernetes environment.

### CODE REVIEW

**Comment by mboersma** [comment]
/hold cancel

I've finally done some local testing with this, by building a Ubuntu 22.04 managed image and provisioning CAPZ clusters. Seems to be working.

**Comment by mboersma** [comment]
@andyzhangx @CecileRobertMichon @jackfrancis please take a look.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by jsturtevant** [comment]
/lgtm
looks like it is building successfully

```
==> Builds finished. The artifacts of successful builds are:
--> vhd-ubuntu-2204: Azure.ResourceManagement.VMImage:
```

This add three more VMs we build for CI. Do we have a plan to remove some at any point?

**Review by andyzhangx — APPROVED** [review]
/lgtm
btw, are we also going to support Mariner 2.0 in this repo? thanks.

**Comment by CecileRobertMichon** [comment]
> This add three more VMs we build for CI. Do we have a plan to remove some at any point?

+1, let's remove 18.04?

**Comment by mboersma** [comment]
At one point discussed publishing 18.04 images [until Ubuntu stops](https://ubuntu.com/about/release-cycle) publishing updates, which I think is April 2023.  But I have no objection to stopping that earlier if we all agree.

I plan to publish Ubuntu 22.04 images for the most recent k8s patch releases as soon as this merges, and then continue to publish 22.04 going forward.

Also, the images we choose to publish are distinct from the tools in this repo. That is, we don't have to remove `make build-azure-vhd-ubuntu-1804` and friends in order to stop publishing those reference images.

**Comment by mboersma** [comment]
> are we also going to support Mariner 2.0 in this repo?

That would be excellent. I don't think anyone is working on this currently, though.

**Comment by jsturtevant** [comment]
> Also, the images we choose to publish are distinct from the tools in this repo. That is, we don't have to remove `make build-azure-vhd-ubuntu-1804` and friends in order to stop publishing those reference images.

Agreed, in addition we can run CI on a subset as well.

**Comment by kkeshavamurthy** [comment]
I vote for keeping Ubuntu 18.04 as it's still being used. Since builds are being run in parallel it should not increase the ci time by too much. 
Also we since a few different behaviors between ubuntu 18 & 20. So the ci is useful.

**Comment by CecileRobertMichon** [comment]
My concern is more $ and subscription quota, each CI job creates a VM for each image type. Right now we have:

```
vhd-centos-7: SUCCESS
vhd-ubuntu-1804: SUCCESS
vhd-windows-2019: SUCCESS
vhd-ubuntu-2004: SUCCESS
vhd-windows-2022-containerd: SUCCESS
vhd-ubuntu-2204: SUCCESS
vhd-windows-2019-containerd: SUCCESS
```

and

```
sig-windows-2019: SUCCESS
sig-centos-7-gen2: SUCCESS
sig-ubuntu-2204: SUCCESS
sig-ubuntu-2004-gen2: SUCCESS
sig-windows-2022-containerd: SUCCESS
sig-centos-7: SUCCESS
sig-flatcar: SUCCESS
sig-ubuntu-1804: SUCCESS
sig-flatcar-gen2: SUCCESS
sig-ubuntu-1804-gen2: SUCCESS
sig-ubuntu-2204-gen2: SUCCESS
sig-windows-2019-containerd: SUCCESS
sig-ubuntu-2004: SUCCESS
```

So 20 VMs for each PR run, which is a lot. If we could make CI a subset of these or at least make some of them optional and not run by default that would help. Not saying we should remove support for 18.04 right away, just concerned about CI.

**Comment by mboersma** [comment]
I can remove `ubuntu-1804` from the `azure_targets.sh` file, which will remove it from CI and other "everything" targets like `build-azure-vhds`.

(Could we do this for `windows-2019` as well? It's mostly been replaced by the `-containerd` flavors is my understanding.)

**Comment by jsturtevant** [comment]
> (Could we do this for windows-2019 as well? It's mostly been replaced by the -containerd flavors is my understanding.)

Yes I think so.  I believe we stopped running dockershim tests (@jackfrancis to confirm) in capz. Especially now that 1.22 is the latest release which supports containerd in capz

**Comment by CecileRobertMichon** [comment]
flatcar failed

/retest
/lgtm

**Pull request merged**
