### PR TITLE
photon: Ensure grub2 and gawk are installed

### PR DESCRIPTION
**Pull request by randomvariable**
## Change description

Can help if user wants to change kernel options post-boot

## Related issues

- Fixes #

### CODE REVIEW

**Comment by mboersma** [comment]
Should we install these by default though? I think the overall idea is to produce minimal images, so you could argue this is a user-specific addition.

**Comment by mboersma** [comment]
Could we make this an optional install that defaults to false, like in #1452?

**Comment by drew-viles** [comment]
I'd agree these should be optional additions as not everyone is going to want/need these packages installed.

**Comment by mboersma** [comment]
Another way to make this an optional install is to use the `debug_tools` variable that we have defined elsewhere (although it only seems to be used currently in Windows builds). I did this in #1458, for example.

**Comment by randomvariable** [comment]
I'll make these changes, apparently the Photon team says grub2-mkconfig isn't used, which is interesting.

**Pull request closed without merging**
