### PR TITLE
Remove unsupported Windows 2004 SAC release

### PR DESCRIPTION
**Pull request by jsturtevant**
What this PR does / why we need it:
Removes all EOL Windows 2004 SAC releases.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #
Towards #1232 

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by mboersma** [comment]
/retest

GitHub rate limiting failure, see #1258.

**Review by mboersma — COMMENTED** [review]
/lgtm

**Comment by AverageMarcus** [comment]
/lgtm

Can we update the PR title to explicitly mention Windows 2004 being removed? Just to make it stand out more in the changelog.

**Comment by jsturtevant** [comment]
/retitle Remove unsupported Windows 2004 SAC release

**Review by mboersma — APPROVED** [review]
/approve

**Pull request merged**
