### PR TITLE
Add fallback for gcloud command

### LINKED ISSUE #1047: make docker-build giving issue - invalid reference format
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
on git clone and in images/capi directory , i ran make docker-build
but i got a error that says :
invalid argument "gcr.io//cluster-node-image-builder-amd64:dev" for "-t, --tag" flag: invalid reference format

**What did you expect to happen:**
docker image creation has to happen

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
- Packer Version:
- Packer Provider:
- Ansible Version: 
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by AverageMarcus**
What this PR does / why we need it:

* Adds fallback value if `gcloud` command fails

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #1047

**Additional context**
N/A

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
I know we needed to change all instances of `k8s.gcr.io` to `registry.k8s.io` (see the [k8s blog](https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/) for reference), but I don't think we need to change references just to `gcr.io`.

I admit to not knowing how the plumbing for all this really works, but:
- the official "change your URLs" notice was only about `k8s.gcr.io`
- I see references to staging images in other projects continue to reference `gcr.io` (for example CAPI and CAPZ, for these same Makefile variables)

**Comment by AverageMarcus** [comment]
Yeah. Now that I think about it, the push registry shouldn't actually change (and the staging aren't even available via `registry.k8s.io`) so I'll update to just include the fallback logic and leave the URLs alone.

**Comment by AverageMarcus** [comment]
Updated to just have the gcloud fallback

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Comment by AverageMarcus** [comment]
@jsturtevant You ok with removing the hold now? 😄

**Comment by mboersma** [comment]
/hold cancel

He's on summer break this week and I think this is a safe, restricted change.

**Pull request merged**
