### PR TITLE
capi: move CI to new resource pool and folder in VMC

### PR DESCRIPTION
**Pull request by chrischdi**
What this PR does / why we need it:

Moves the resources created inside CI to a new location.
We currently cleanup the environment and change some structure.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by drew-viles** [comment]
Apologies in advanced for the potentially silly question as I've not touched anything on the OVA side so need to clarify things in my head. I can see the ci completed just fine so, is this just a cosmetic change in terms of the folder that is defined in the `vsphere.json` file?

**Comment by chrischdi** [comment]
Thanks for asking.

Yes this is just cosmetical on the server side. currently its using the already existing:
* vSphere Resource Pool `Compute-ResourcePool/ci-image-builder` and after this PR it will use `Compute-ResourcePool/image-builder`
* vSphere Storage Folder `Workloads/ci/image-builder` and after this PR it will use `Workloads/image-builder`

We did move this already some weeks ago but now finalised the naming.

Previous PR:
* https://github.com/kubernetes-sigs/image-builder/pull/1288

**Comment by drew-viles** [comment]
Cool. thanks for confirming that for me.
In which case I see no issues with what I'm looking at so I'll stick my stamp on it.

/approve

**Review by drew-viles — APPROVED** [review]

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
