### PR TITLE
Merge https://github.com/kubernetes/kube-deploy into images/kube-deploy

### LINKED ISSUE #4: Import kube-deploy/image-builder implementation
@justinsb Could you please import the kube-deploy implementation into `images/kube-deploy`

If you are too busy feel free to assign it back to me

/assign @justinsb

### PR DESCRIPTION
**Pull request by justinsb**
Fix #4

### CODE REVIEW

**Comment by justinsb** [comment]
Looks like we're going to have to force-merge this one...  generated using the following if you want to verify:

```
git remote add kubedeploy https://github.com/kubernetes/kube-deploy
git fetch kubedeploy
git co -b import_kubedeploy
git merge -s ours --no-commit --allow-unrelated-histories kubedeploy/master 
git read-tree --prefix=images/kube-deploy/ -u kubedeploy/master
git commit -m "subtree merge https://github.com/kubernetes/kube-deploy into images/kube-deploy"
```

**Comment by justinsb** [comment]
(I assume one of you has the magic merge permissions.. I also have them if it is just about lacking permissions to push the button, but I wouldn't do that without /lgtm /approve)

**Comment by figo** [comment]
> Looks like we're going to have to force-merge this one... generated using the following if you want to verify:
> 
> ```
> git remote add kubedeploy https://github.com/kubernetes/kube-deploy
> git fetch kubedeploy
> git co -b import_kubedeploy
> git merge -s ours --no-commit --allow-unrelated-histories kubedeploy/master 
> git read-tree --prefix=images/kube-deploy/ -u kubedeploy/master
> git commit -m "subtree merge https://github.com/kubernetes/kube-deploy into images/kube-deploy"
> ```

/lgtm

**Comment by detiber** [comment]
lgtm as well

**Comment by justinsb** [comment]
So are we OK for me to "Merge pull request"?  Just want to be double-sure ... @timothysc ?

**Comment by detiber** [comment]
+1 from me, @timothysc is currently on PTO

**Comment by justinsb** [comment]
OK - thanks!  Merged :-)

**Pull request merged**
