### PR TITLE
Remove windows docker

### PR DESCRIPTION
**Pull request by jsturtevant**
What this PR does / why we need it:

Dockershim was completly removed in 1.24.  The docker support that was added here was relied on docker shim.  

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
It might be possible to add https://www.mirantis.com/software/mirantis-container-runtime/ in the future but no testing has been done and the approach would be different than what we have here.

### CODE REVIEW

**Comment by jsturtevant** [comment]
/hold 
Want to give it a bit of time before merge for any concerns

**Review by AverageMarcus — COMMENTED** [review]
/lgtm

**Review by mboersma — COMMENTED** [review]
/lgtm

**Comment by jsturtevant** [comment]
Will give it another couple weeks then release the hold unless I hear anything.  Thanks!

**Review by mboersma — APPROVED** [review]
/approve

**Pull request merged**
