### PR TITLE
Add NetworkConfigPlugin to VMware cloudbase-init plugin list

### LINKED ISSUE #1434: Enable NetworkConfigPlugin for cloudbase-init in VMware Windows OVA to allow static IP configuration
## Is your feature request related to a problem? Please describe.
We have a PR in upstream cloudbase-init for feature parity with cloudinit
for VMware Datasource at launch.
It allows the Windows node VM to configure network based on the VM instance metadata
(`guestinfo.metadata`) in VMware environment.
We need to enable NetworkConfigurationPlugin for Windows OVA for those scenarios
such as static IPs are used.

## Additional context
Note:
1. The current cloudbase-init PR is still pending for review.
    NetworkConfigurationPlugin in current version has no action so no negative impact when it is enabled while old cloudbase-init release is used.
2. The UserdataPlugin needs to be run after NetworkConfigurationPlugin to make sure userdata is applied after the network configuration is done.

Refer to
https://review.opendev.org/c/x/cloudbase-init/+/913734
for related changes in cloudbase-init.

---

/kind feature

### PR DESCRIPTION
**Pull request by laozc**
This commits add the NetworkConfigPlugin to VMware cloudbase-init plugins list for Windows Node VM, which allows Windows Node VM to configure static IP address at launch.
Note: There is a pending upstream contribution for cloudbase-init to add Network Configuration support to VMware data source and keep feature parity with cloudinit.

## Related issues

- Fixes #1434

### CODE REVIEW

**Comment by AverageMarcus** [comment]
> Note: There is a pending upstream contribution for cloudbase-init to add Network Configuration support to VMware data source and keep feature parity with cloudinit.

Do we need to wait for this upstream change? Can you provide a link to it here?

**Comment by laozc** [comment]
In the current release `NetworkConfigPlugin` simply has no-op in VMware environment so no side-effect if we merge this PR first. It needs an updated version of cloudbase-init to work with static IP assignment.

For the work at cloudbase-init side regarding the static IP support, you may check
https://review.opendev.org/c/x/cloudbase-init/+/913734

**Comment by laozc** [comment]
Also, the network related plugins are moved before the `UserDataPlugin` to ensure network related configuration is done before we call `kubeadm` in user data for CAPI.

**Review by mboersma — COMMENTED** [review]
/lgtm

**Pull request merged**
