### PR TITLE
add owners file for windows

### PR DESCRIPTION
**Pull request by jayunit100**

### CODE REVIEW

**Review by codenrhoden — COMMENTED** [review]
I like the idea of having a seperate OWNERS file for windows related roles here. I think maybe creating a new `image-builder-windows-maintainers` alias in `OWNERS_ALIASES` might be a good approach? We've tried to avoid naming individuals any place but at the top level. I would then put @jsturtevant and @perithompson  in that alias.

/cc @CecileRobertMichon @jsturtevant

**Comment by CecileRobertMichon** [comment]
> I like the idea of having a seperate OWNERS file for windows related roles here. I think maybe creating a new image-builder-windows-maintainers alias in OWNERS_ALIASES might be a good approach? We've tried to avoid naming individuals any place but at the top level. I would then put @jsturtevant and @perithompson in that alias.

+1

**Comment by codenrhoden** [comment]
sounds like there is some consensus here, @jayunit100, if you can find the time to make the suggested change. Thanks for this!

**Comment by jayunit100** [comment]
im going to close this so the img builder folks can implement it ,   not really my wheelhouse to define OWNERS files :)

**Pull request closed without merging**
