### PR TITLE
Bump packer-provisioner-goss to 3.0.3 & packer to 1.7.2

### PR DESCRIPTION
**Pull request by berendt**
Signed-off-by: Christian Berendt <berendt@23technologies.cloud>

### CODE REVIEW

**Comment by detiber** [comment]
It's not clear to me what the failure was in the `pull-azure-vhds` job, @CecileRobertMichon might have more context.

**Comment by CecileRobertMichon** [comment]
```
Error: Failed to initialize build "vhd-ubuntu-2004"

error initializing provisioner 'goss': Unknown address type: 0
```

from the logs

**Comment by perithompson** [comment]
Annoyingly I've had to patch the provisioner, do you want me to  raise a separate PR for 3.0.3?

**Comment by perithompson** [comment]
@berendt @detiber  I think the checksums might be of the tar and not of the executable, I am bumping up the version to 3.0.3 in #563 and those messages look the same as what I was seeing until I changed for the shasum of the executables

**Review by codenrhoden — COMMENTED** [review]
This can't be bumped to 3.0.x without also bumping Packer to 1.7.x.

We do want to do this bump, so I would suggest bumping the GOSS provisioner to 3.0.3 and Packer to 1.7.2 (the latest of both).

I have a feeling that it will be a bit longer before #563 merges in, so it would be nice to get these bumped sooner.

**Comment by codenrhoden** [comment]
@cpanato Just want to make you aware of https://github.com/kubernetes/test-infra/pull/21753 and https://github.com/kubernetes-sigs/image-builder/pull/586. We're planning to put all CI scripts into `images/capi/scripts` now, and there are a couple of PRs related to moving them. It would be nice if the GCE script can go there to start with.

**Comment by codenrhoden** [comment]
/lgtm
/approve

Apologies for the most recent comment in here. That was meant for a different PR. :)
Thank you @berendt !

**Comment by cpanato** [comment]
@codenrhoden sorry for the delay to reply, sounds good, I will refactor the PR to add there, thanks for the headsup

**Pull request merged**
