### PR TITLE
Bump Ubuntu ISO 18.04.4 in OpenStack provider

### PR DESCRIPTION
**Pull request by hidekazuna**
This PR is followup PR of #225, updates the ubuntu ISO to 18.04.4 in OpenStack provider.

### CODE REVIEW

**Comment by jichenjc** [comment]
looks good, do we plan to consider this to 20.04 as well later on?

**Comment by hidekazuna** [comment]
> looks good, do we plan to consider this to 20.04 as well later on?

Issue has been already raised #217 .

**Pull request merged**
