### PR TITLE
Add support for RHEL 8 RAW image builds

### PR DESCRIPTION
**Pull request by abhay-krishna**
Adding support for RHEL 8 RAW image builds.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
@mboersma is the `pull-ova-all` presubmit being flaky? It fails on photon-3, photon-4, centos-7, I checked the logs in the artifacts directory but they don't seem to be related to my changes.

**Comment by kkeshavamurthy** [comment]
/lgtm
@SanikaGawhane Is looking into the photon failures. Ubuntu seems like a flake.

**Comment by kkeshavamurthy** [comment]
@abhay-krishna 
#1121 should fix the photon ci failures. Please rebase.

**Comment by abhay-krishna** [comment]
> @abhay-krishna #1121 should fix the photon ci failures. Please rebase.

Thanks @kkeshavamurthy! Seems like that PR didn't get an `approved` label.

**Pull request merged**
