### PR TITLE
[WIP] capi: support Flatcar OVA images

### PR DESCRIPTION
**Pull request by dongsupark**
Add Flatcar as one of the distros in the VMware OVA image builder.

Would rely on https://github.com/flatcar-linux/flatcar-packer-qemu/pull/4 .

_please do not merge. work-in-progress._

### CODE REVIEW

**Comment by dongsupark** [comment]
Hmm, sorry for noise.
Closing.

**Comment by jzhoucliqr** [comment]
@dongsupark Were you able to get the flatcar ova working? We are interested in this, would be curious to know what are the remaining work to be done.

**Comment by dongsupark** [comment]
@jzhoucliqr 
Thanks for the comment.
Yes, I was able to get it working, months ago.
Though in order to keep the original Flatcar support PR as small as possible, we did not include the OVA part in the upstream PR.

However, this PR was just a bogus PR that I created by mistake.
The actual up-to-date PR is https://github.com/kinvolk/image-builder/pull/11 .
I would need to rebase that PR on top of the current master branch, and test it again.
Once I do that, I will create an upstream PR.

**Comment by jzhoucliqr** [comment]
@dongsupark That's great! I can also help testing when PR is ready. Thanks!

**Pull request closed without merging**
