### PR TITLE
update cni-plugins to v1.3.0

### LINKED ISSUE #1196: Update CNI plugins to v.1.3.0
**Is your feature request related to a problem? Please describe.**

CNI plugins 1.3.0 [is released](https://github.com/containernetworking/plugins/releases/tag/v1.3.0) but does not appear yet on the location that image-builder uses.

Update CNI plugins to 1.3.0 once they appear at https://storage.googleapis.com/k8s-artifacts-cni/

**Describe the solution you'd like**

This issue is mostly a reminder to check https://storage.googleapis.com/k8s-artifacts-cni/ every now and then

**Describe alternatives you've considered**

**Additional context**

/kind feature

### PR DESCRIPTION
**Pull request by kranurag7**
this commit updates cni plugin to use v1.3.0

What this PR does / why we need it:

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

Fixes #1196 

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Review by AverageMarcus — COMMENTED** [review]
/ok-to-test
/lgtm

**Comment by mboersma** [comment]
This is hitting a similar error to what I saw when I tried this [previously](https://github.com/kubernetes-sigs/image-builder/issues/1196#issuecomment-1791068444):

```
[0;32m    vsphere-clone: fatal: [default]: FAILED! => {"changed": true, "cmd": ["tdnf", "install", "kubelet-1.26.7", "kubeadm-1.26.7", "kubectl-1.26.7", "kubernetes-cni-1.3.0", "--nogpgcheck", "-y"], "delta": "0:00:00.600257", "end": "2024-01-12 15:58:46.391843", "msg": "non-zero return code", "rc": 243, "start": "2024-01-12 15:58:45.791586", "stderr": "kubernetes-cni-1.3.0 package not found or not installed\nError(1011) : No matching packages"
```

I wonder if kubernetes-cni 1.3.0 is only packaged for certain versions of Kubernetes (perhaps more recent than 1.26.7)?

**Comment by kranurag7** [comment]
Yes. The changes introduced via this patch is for 1.29 series of Kubernetes. 


- _Kubernetes repositories for v1.28 and onwards are going to have published only versions that are used by that Kubernetes minor release_
  - _Speaking of v1.28, only kubernetes-cni 1.2.0 and cri-tools v1.28 are going to be available in the repository for Kubernetes v1.28_
  - _Similar for v1.29, we only plan on publishing cri-tools v1.29 and whatever kubernetes-cni version is going to be used by Kubernetes v1.29_

Ref: https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/ 

--- 
To reproduce 
```bash
$ echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ / 
$ sudo apt search kubernetes-cni
Sorting... Done
Full Text Search... Done
kubernetes-cni/unknown 1.2.0-2.1 amd64
  Binaries required to provision kubernetes container networki

# with 1.29 
$ echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
$ sudo apt update
$ sudo apt search kubernetes-cni
Sorting... Done
Full Text Search... Done
kubernetes-cni/unknown 1.3.0-1.1 amd64
  Binaries required to provision kubernetes container networking
```
Let me know if there's an easier way to know the exact version cni-plugins debs a particular Kubernetes supports. As of now, I was not able to find it very easily.

**Comment by mboersma** [comment]
Somehow we should make the default values conditional so that `kubernetes-cni` v1.2.0 continues to be used for k8s < v1.29.0. I think that's the most user-friendly thing but I'm not sure the best way to accomplish that.

See also #1363.

The default version of Kubernetes used here in e2e should probably also be bumped at this point, although not to v1.29; we tend to stay two versions back.

> Let me know if there's an easier way to know the exact version of cni-plugins...

I haven't found a good way. I usually start a Docker container for a given Linux distro and then run the `apt` or `rpm` commands and see what versions actually work.

**Comment by mboersma** [comment]
/close

See #1385.

@kranurag7 thanks for working on this! Please let me know if the approach in #1385 (don't require a specific `kubernetes-cni` version when installed through a package manager) works for you.

**Pull request closed without merging**
