### PR TITLE
update the way to install cloud-init

### PR DESCRIPTION
**Pull request by outscale-hmi**
## Change description
This PR solve the mismatch of cloud-init version and install the official version with ansible rather than passing by a packaged version

### CODE REVIEW

**Comment by mboersma** [comment]
Thanks @outscale-hmi! Could you [click here](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/20677499/195487209/1440/#/?version=2) to sign the Contributor License Agreement?

**Review by mboersma — APPROVED** [review]
/lgtm

/assign @AverageMarcus

**Review by AverageMarcus — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
