### PR TITLE
Remove windows-2019 and -2025 targets from CI

### PR DESCRIPTION
**Pull request by mboersma**
## Change description

Removes the Azure windows-2019 and windows-2025 targets from CI runs, since they are both failing and blocking unrelated PRs from merging.

## Related issues

- Refs #1602
- Refs #1603

### CODE REVIEW

**Comment by AverageMarcus** [comment]
@mboersma Are these targets actually broken or just in CI? As in, do we want to drop support for building these completely?

**Comment by mboersma** [comment]
/test pull-azure-sigs

@AverageMarcus, as far as I can tell, the windows-2019 targets are broken and maybe we should remove them altogether, although @jsturtevant should weigh in. The windows-2025 target supposedly only fails in CI, and needs to be fixed and supported.

**Comment by mboersma** [comment]
/test pull-azure-sigs

Two unrelated flakes and a timeout. :-( Not sure why things are going badly here, I'm running `./images/capi/scripts/ci-azure-e2e.sh` locally to see if I can reproduce.

**Comment by jsturtevant** [comment]
/lgtm
/approve

The time of the failures aligns with patch Tuesday last week. 2019 is technically EOL and only receiving security patches right now so likely ok to remove from CI.

@TinaMor fyi on 2025, hopefully we just need to increase the timeout to make this pass.

**Pull request merged**
