### PR TITLE
Re-establish prior order of the cloudbase-init plugins

### PR DESCRIPTION
**Pull request by jsturtevant**
What this PR does / why we need it:

The order of the cloudbase-init plugins matters. Since we can't know the order required for all platforms we share some of the duplication of plugins. After https://github.com/kubernetes-sigs/image-builder/commit/25eba9cad267b6eebabde77ad70c53da30ad908e the order for Azure vm's changes and broke ssh https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3232. This moves the order back to the order prior to the PR and removes the duplicate entries for a couple platforms.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): **Fixes** https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3232

**Additional context**
Add any other context for the reviewers

/sig windows 
/assign @marosset @joekr @mboersma

### CODE REVIEW

**Review by marosset — APPROVED** [review]
/lgtm

Good find!

**Comment by jsturtevant** [comment]
/hold
doing some additional validation

**Comment by jsturtevant** [comment]
went through the logs and found it is working:

```
2023-03-15 18:04:52.049 3108 INFO cloudbaseinit.init [-] Reporting provisioning completed
2023-03-15 18:04:52.049 3108 DEBUG cloudbaseinit.metadata.services.azureservice [-] Health data: b"<?xml version='1.0' encoding='utf-8'?>\n<Health><GoalStateIncarnation>1</GoalStateIncarnation><Container><ContainerId>4703b635-1b90-48cc-85d3-d0439ca28ead</ContainerId><RoleInstanceList><Role><InstanceId>33df91b9-5ba4-447d-b3c0-9655b359f5ec._testvm-md-d92nv</InstanceId><Health><State>Ready</State></Health></Role></RoleInstanceList></Container></Health>" _post_health_status C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\metadata\services\azureservice.py:210
```

And the output of the additional check in the pipeline is:

```
+ az vm list -g capi-testvmimage-31533
+ jq -e '.[].provisioningState == "Succeeded"'
true
true
```

**Comment by jsturtevant** [comment]
this is ready, can remove hold once you review @mboersma 
/assign @mboersma

**Review by mboersma — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
