### PR TITLE
Fix distro-version for ubuntu1804 OVAs

### PR DESCRIPTION
**Pull request by SanikaGawhane**
What this PR does / why we need it:

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Comment by codenrhoden** [comment]
🤦  doh.

/lgtm
/approve

**Comment by kkeshavamurthy** [comment]
Thanks for catching it @SanikaGawhane

**Pull request merged**
