### PR TITLE
update CAPG owners alias

### PR DESCRIPTION
**Pull request by cpanato**
What this PR does / why we need it:

- update CAPG owners alias
to match what we have in CAPG repo

/assign @fabriziopandini @richardcase @dims 

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm

Compared to https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/OWNERS_ALIASES#L24

**Comment by cpanato** [comment]
need your approval here as well @mboersma  :)

**Comment by cpanato** [comment]
thanks @mboersma

**Pull request merged**
