### PR TITLE
Add vultr packer provider

### PR DESCRIPTION
**Pull request by happytreees**
## Change description
This PR adds the Vultr Packer Provider to the repo to allow users to provision CAPI images on Vultr.

### CODE REVIEW

**Review by AverageMarcus — COMMENTED** [review]
Looks good! 😁  Thanks @happytreees 

Would you mind adding a new section to the docs to cover this too? 🙏 (e.g. https://github.com/kubernetes-sigs/image-builder/tree/main/docs/book/src/capi/providers)

**Comment by happytreees** [comment]
> Looks good! 😁 Thanks @happytreees
> 
> Would you mind adding a new section to the docs to cover this too? 🙏 (e.g. https://github.com/kubernetes-sigs/image-builder/tree/main/docs/book/src/capi/providers)

Sorry about that @AverageMarcus ! Just added it in.

**Review by AverageMarcus — COMMENTED** [review]
/ok-to-test
/lgtm
/assign @drew-viles

**Comment by drew-viles** [comment]
Sorry, I'm going to be a pain now! Can you squash those commits down as well please?

**Comment by happytreees** [comment]
@drew-viles No worries! Just pushed squashed commit.

**Review by drew-viles — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
