### PR TITLE
Updating links to Rocky Linux 8.5

### PR DESCRIPTION
**Pull request by davidjumani**
What this PR does / why we need it:

This PR updates the Rocky Linux ISO to the 8.5 version as the 8.4 version is no longer available online
It also updates the repo as the 8.4 repo is no longer available

### CODE REVIEW

**Comment by tobiasgiese** [comment]
/ok-to-test

thanks @davidjumani 🙂

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Tests appear to have passed, this was manually tested by us too. cc @tobiasgiese @srm09 - pl help review, merge this.

**Comment by kkeshavamurthy** [comment]
Thanks for updating this. 
/approve

**Pull request merged**
